FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# MST Public API

De MST public API faciliteert het doorzoeken en opvragen van toegelaten biocides, gewasbeschermingsmiddelen en toevoegingsstoffen.

## Toelatingen summary [/toelatingen{?filter%5BmiddelNaam%5D,filter%5BmiddelStatus%5D,filter%5BcategorieType%5D,filter%5BtoelatingNummer%5D,filter%5BwerkzameStoffen%5D,filter%5BbeschermStoffen%5D,filter%5BcasNummer%5D,filter%5BtoelatingHouder%5D,filter%5BexpiratieDatumVan%5D,filter%5BexpiratieDatumTot%5D,filter%5BdatumOndertekeningVan%5D,filter%5BdatumOndertekeningTot%5D,sort,page%5Bsize%5D,page%5Bnumber%5D}]


### Opvragen Toelatingen [GET]

Voor het opvragen van toelatingen maakt deze API gebruik van de [jsonapi](http://jsonapi.org/recommendations/) standaard.
jsonapi maakt voor zommige query parameters gebruik van een categorie typering. Dwz de categorie, b.v. `filter` gevolgd door `[` veldnaam `]`. 
De hier gebruikte categorieen zijn:
- Filteren: `filter[veldNaam]`
- Paginatie: `page[number]` en `page[size]`. Deze parameters dienen samen gebruikt te worden. B.v. `/toelatingen?page[size]=25&page[number]=5` slaat de toelatingen 0-100 (pagina 1 - 4) over and retourneert 101-125

Omdat in query parameter blokhaken (`[]`) niet toegestaan zijn dienen deze url-encode te worden. 
Dus b.v. `filter[veldNaam]` wordt daadwerkelijk: `filter%5BveldNaam%5D`

+ Parameters
    + filter%5BmiddelNaam%5D (string, optional) - de naam van het middel of een deel ervan. In de zoekvraag wordt dit vertaald naar `contains(naam)` niet hoofdlettergevoelig  
    + filter%5BmiddelStatus%5D (enum[middelStatus], optional) - de status van een middel. Meerdere middel statussen worden in de zoekvraag vertaald naar: `OR`. 
        + Members
            + `Toegelaten`
            + `Vervallen`
        + Default: `Toegelaten`, `Vervallen`
    + filter%5BcategorieType%5D (enum[categorieType], optional) - het categorie type van een middel. Meerdere categorie types worden in de zoekvraag vertaald naar: `OR`. 
        + Members
            + `Biocide`
            + `Gewas`
            + `ToevoegingsStof`
        + Default: `Biocide`,`Gewas`,`ToevoegingsStof`
    + filter%5BtoelatingNummer%5D (string, optional) - het toelating nummer van het middel (nl of eu???)
    + filter%5BwerkzameStoffen%5D (number, optional) - id's van werkzamestoffen, koma separated. Meerdere id's worden in de zoekvraag vertaald naar: `OR`.
    + filter%5BbeschermStoffen%5D (number, optional) - id's van beschermstoffen, koma separated. Meerdere id's worden in de zoekvraag vertaald naar: `OR`.
    + filter%5BcasNummer%5D (string, optional)  - stof id van geselecteerde stof ???
    + filter%5BtoelatingHouder%5D (string, optional) - id's van toelatinghouders, koma separated. Meerdere id's worden in de zoekvraag vertaald naar: `OR`.
    + filter%5BexpiratieDatumVan%5D (string, optional) - expiratie datum vanaf in formaat: `yyyy-MM-dd` 
    + filter%5BexpiratieDatumTot%5D (string, optional) - expiratie datum tot en met in formaat: `yyyy-MM-dd` 
    + filter%5BdatumOndertekeningVan%5D (string, optional) - datum ondertekening vanaf in formaat: `yyyy-MM-dd` 
    + filter%5BdatumOndertekeningTot%5D (string, optional) - datum ondertekening tot en met in formaat: `yyyy-MM-dd`
    + sort (string optional) - koma separated lijst van veldnamen waarop gesorteerd dient te worden. Default is de sortering _oplopend_. Door een `-` aan de veldnaam toe te voegen is de sortering _aflopend_. B.v. `sort=naam,toelating.toelatingNummer,-toelating.datumOndertekening`.
        Er kunnen op de volgende velden gesorteerd worden: `naam`, `categorieType`, `toelating.toelatingNummer`, `toelating.expiratieDatum`, `toelating.datumOndertekening` 
    + page%5Bsize%5D (number, optional) -  aantaal toelatingen per pagina
        + Default: `50`
    + page%5Bnumber%5D (number, optional) - het pagina nummer van de geretourneerde toelatingen  ( deze is "zero-based", dwz de eerste pagina is 1, niet 0)
        + Default: `1`

+ Response 200 (application/json)

            {
               "meta": {
                "total-count": 1255,
                "pageSize":25,
                "pageNumber":3
            },
            "data": [
              {
                "id" : "23456",
                "naam": "Mirazyl",
                "categorieType": "Biocide",
                "toelating": {
                  "toelatingNummer": "NL-0006252-0000",
                  "expiratieDatum": "2019-02-10T00:00:00.000+01:00",
                  "datumOndertekening": "2015-01-08T00:00:00.000+01:00"
                }
              },
              {
                "id" : "23457",
                "naam": "Hema Goodbye Mosquito Anti-muggen roller with DEET",
                "categorieType": "Biocide",
                "toelating": {
                  "toelatingNummer": "12569",
                  "expiratieDatum": "2017-01-18T00:00:00.000+01:00",
                  "datumOndertekening": "2013-01-17T00:00:00.000+01:00"
                }
              },
              {
                "id" : "55555",
                "naam": "TRIFOCIDE VLOEIBAAR DNOC",
                "categorieType": "Gewas",
                "toelating": {
                  "toelatingNummer": "3204",
                  "expiratieDatum": "2020-01-01T00:00:00.000+01:00",
                  "datumOndertekening": "2013-05-13T00:00:00.000+01:00"
                }
              },
              {
                "id" : "77777",
                "naam": "Biopower",
                "categorieType": "ToevoegingsStof",
                "toelating": {
                  "toelatingNummer": "13760",
                  "expiratieDatum": "8888-08-07T00:00:00.000+01:00",
                  "datumOndertekening": "2014-06-17T00:00:00.000+01:00"
                }
              }
            ]
            }
        

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }