FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# MST Public API

De MST public API faciliteert het doorzoeken en opvragen van toegelaten biocides, gewasbeschermingsmiddelen en toevoegingsstoffen.

Deze API maakt gebruik van de [jsonapi](http://jsonapi.org/recommendations/) standaard.

[jsonapi](http://jsonapi.org/recommendations/) maakt voor zommige query parameters gebruik van een typering. B.v. het type `filter` gevolgd door `[` veldnaam `]`. 
De hier gebruikte types zijn:
- Filteren: `filter[veldNaam]`
- Paginatie: `page[offset]` en `page[limit]`. Deze parameters dienen samen gebruikt te worden. B.v. `/toelatingen?page[offset]=100&page[limit]=25` slaat de toelatingen 0-100 over and retourneert 101-125

**Belangrijk**

Omdat in query parameters blokhaken (`[]`) niet toegestaan zijn dienen deze url-encode te worden. 
Dit betekent dat b.v. `filter[veldNaam]` vertaald dient te worden naar: `filter%5BveldNaam%5D`

## Toelatingen summary [/public-api/1.0/toelatingen{?filter%5BmiddelNaam%5D,filter%5BmiddelStatus%5D,filter%5BcategorieType%5D,filter%5BtoelatingNummer%5D,filter%5BwerkzameStoffen%5D,filter%5BbeschermStoffen%5D,filter%5BtoelatingHouder%5D,filter%5BbiocideToepassingInfo%5D,filter%5BbiocideDoelorganismen%5D,filter%5BgewasToepassingsgebieden%5D,filter%5BgewasToepassingsgebiedenLang%5D,filter%5BgewasDoelorganismen%5D,filter%5BgewasToepassingslocaties%5D,filter%5BgewasAardWerkingen%5D,filter%5BexpiratieDatumVan%5D,filter%5BexpiratieDatumTot%5D,filter%5BdatumOndertekeningVan%5D,filter%5BdatumOndertekeningTot%5D,sort,page%5Boffset%5D,page%5Blimit%5D}]

Met deze service kunnen toelatingen op basis van een groot aantal parameters doorzocht worden. Daarnaast biedt deze service sortering en paginatie.

+ Parameters
    + filter%5BmiddelNaam%5D (string, optional) - de naam van het middel of een deel ervan.  In de zoekvraag wordt dit vertaald naar `contains naam,` niet hoofdlettergevoelig.
    + filter%5BmiddelStatus%5D (enum%5BmiddelStatus%5D, optional) - de status van een middel. Meerdere middel statussen worden in de zoekvraag vertaald naar: `OR`.
        + Members
            + `Valid`
            + `Expired`
    + filter%5BcategorieType%5D (enum%5BcategorieType%5D, optional) - het categorie type van een middel. Meerdere categorie types worden in de zoekvraag vertaald naar: `OR`.
        + Members
            + `Biocide`
            + `Gewas`
            + `ToevoegingsStof`
    + filter%5BtoelatingNummer%5D (string, optional) - het toelating nummer van het middel, nl of eu
    + filter%5BwerkzameStoffen%5D (number, optional) - id's van werkzamestoffen, koma separated. Meerdere id's worden in de zoekvraag vertaald naar: `OR`.
    + filter%5BbeschermStoffen%5D (number, optional) - id's van beschermstoffen, koma separated. Meerdere id's worden in de zoekvraag vertaald naar: `OR`.
    + filter%5BtoelatingHouder%5D (string, optional) - id's van toelatinghouders, koma separated. Meerdere id's worden in de zoekvraag vertaald naar: `OR`.
    + filter%5BbiocideToepassingInfo%5D (string, optional) - vrije tekst die zoekt in de toepassingen informatie van biocides.
    + filter%5BbiocideDoelorganismen%5D (number, optional) - id's van triviale doelorganisme namen, koma separated. Meerdere id's worden in de zoekvraag vertaald naar: `OR`.
    + filter%5BgewasDoelorganismen%5D (number, optional) - id's van geclaimde organismen, koma separated. Meerdere id's worden in de zoekvraag vertaald naar: `OR`.
    + filter%5BgewasToepassingsgebieden%5D (string, optional) - namen van gewassen gevolgd door locatie in de DTG hierarchie zijnde `groep, subgroep, gewas`, geconcateneerd met `::`. Meerdere paden worden koma separated, deze worden in de zoekvraag vertaald naar: `OR`. Voorbeeld: Toepassingsgebieden voor een gewasbeschermingsmiddel voor `Appel` of `Steenvruchten`: `Appel::gewas,Steenvruchten::subgroep`.
    + filter%5BgewasToepassingsgebiedenLang%5D: nl (enum[lang], optional) - language parameter voor toepassingsgebieden met de afkorting van de gewenste taal. Default is `nl`.
        + Members
                + `nl`
                + `en`
    + filter%5BgewasToepassingslocaties%5D (number, optional) - id's van toepassingslocaties, koma separated. Meerdere id's worden in de zoekvraag vertaald naar: `OR`.
    + filter%5BgewasAardWerkingen%5D (number, optional) - id's van aard werkingen, koma separated. Meerdere id's worden in de zoekvraag vertaald naar: `OR`.
    + filter%5BexpiratieDatumVan%5D (string, optional) - expiratie datum vanaf in formaat: `yyyy-MM-dd`
    + filter%5BexpiratieDatumTot%5D (string, optional) - expiratie datum tot en met in formaat: `yyyy-MM-dd`
    + filter%5BdatumOndertekeningVan%5D (string, optional) - datum ondertekening vanaf in formaat: `yyyy-MM-dd`
    + filter%5BdatumOndertekeningTot%5D (string, optional) - datum ondertekening tot en met in formaat: `yyyy-MM-dd`
    + sort (string optional) - koma separated lijst van veldnamen waarop gesorteerd dient te worden. Default is de sortering _oplopend_. Door een '`-`' aan de veldnaam toe te voegen is de sortering _aflopend_. B.v. `sort=naam,-datumOndertekening`.
        Er kunnen op de volgende velden gesorteerd worden: `naam`, `categorieType`, `toelatingNummer`, `expiratieDatum`, `datumOndertekening`
    + `page%5Boffset%5D` (number, optional) -  aantal toelatingen die overgeslagen worden voordat het resultaat geretourneerd wordt
        + Default: `0`
    + `page%5Blimit%5D` (number, optional) - aantal te retourneren toelatingen
        + Default: `50`

### Opvragen Toelatingen [GET]

+ Response 200 (application/json)

            {
               "meta": {
                "total": 1255,
                "offset":0,
                "limit":50
            },
            "data": [
              {
                "id" : "23456",
                "naam": "Mirazyl",
                "categorieType": "Biocide",
                "toelatingNummer": "NL-0006252-0000",
                "expiratieDatum": "2019-02-10T00:00:00.000+01:00",
                "datumOndertekening": "2015-01-08T00:00:00.000+01:00"
              },
              {
                "id" : "22222",
                "naam": "Hema Goodbye Mosquito Anti-muggen roller with DEET",
                "categorieType": "Biocide",
                "toelatingNummer": "12569",
                "expiratieDatum": "2017-01-18T00:00:00.000+01:00",
                "datumOndertekening": "2013-01-17T00:00:00.000+01:00"
              },
              {
                "id" : "55555",
                "naam": "TRIFOCIDE VLOEIBAAR DNOC",
                "categorieType": "Gewas",
                "toelatingNummer": "3204",
                "expiratieDatum": "2020-01-01T00:00:00.000+01:00",
                "datumOndertekening": "2013-05-13T00:00:00.000+01:00"
              },
              {
                "id" : "88888",
                "naam": "Biopower",
                "categorieType": "ToevoegingsStof",
                "toelatingNummer": "13760",
                "expiratieDatum": "8888-08-07T00:00:00.000+01:00",
                "datumOndertekening": "2014-06-17T00:00:00.000+01:00"
              }
            ]
        }
        

## Toelating [/public-api/1.0/toelatingen/{id}]

Het opvragen van een toelating kan resulteren in 3 verschillende types antwoorden:
- Toelating voor Bicode
- Toelating voor Gewasbestrijdingsmiddel
- Toelating voor ToevoegingsStof

Het `categorieType` in het antwoord document geeft aan welk type toelating het betreft. De waardes hiervoor zijn:
- `Biocide`
- `Gewas`
- `ToevoegingsStof`

+ Parameters
    + id: 23456 (number, required) - id van het middel.

### Opvragen Toelating  [GET]

+ Response 200 (application/json)

        {
          "data": {
              "id" : "7544cbc1eff64f79a5185a7f4afca547",
              "naam" : "Wizard",
              "categorieType" : "Biocide",
              "gebruiker" : "Professioneel",
              "toelatingHouder" : {
                "companyName" : "BAYER",
                "address" : {
                  "street" : "Bayernslaan",
                  "number" : "888",
                  "postalcode" : "5635 AE",
                  "city" : "Ede",
                  "country" : "England"
                }
              },
              "toelating" : {
                "toelatingNummer" : {
                  "nl" : 121212,
                  "eu" : "EU-1234-9999-000",
                  "ingangsDatum" : "2016-08-02T08:46:41.662+02:00"
                },
                "expiratieDatum" : "2019-08-02T08:46:41.663+02:00",
                "opgebruikTermijn" : "2018-08-02T08:46:41.663+02:00",
                "afleverTermijn" : "2019-08-02T08:46:41.663+02:00",
                "gebruiksvoorschriften" : [ {
                  "gebruiker" : "Professioneel",
                  "documenten" : [ {
                    "document" : {
                      "docId" : "doc-1",
                      "documentNaam" : "Besluit.doc"
                    },
                    "ingangsDatum" : "2016-08-02T08:46:41.675+02:00",
                    "expiratieDatum" : "2019-08-02T08:46:41.663+02:00"
                  } ]
                } ]
              },
              "samenstellingen" : {
                "formuleringType" : {
                  "id" : 1,
                  "code" : "AE",
                  "descriptionNL" : "Aerosol spuitbus",
                  "descriptionEN" : "Aerosol dispenser"
                },
                "stoffen" : [ {
                  "stof" : {
                    "id" : 19,
                    "naamNL" : "acefaat",
                    "naamEN" : "acephate",
                    "ecNummer" : "250-241-2",
                    "casNummer" : "30560-19-1"
                  },
                  "functie" : {
                    "id" : 40,
                    "descriptionNL" : "Werkzame stof",
                    "descriptionEN" : "Active Ingredient"
                  },
                  "gehalte" : "456",
                  "concentratie" : {
                    "id" : 20,
                    "unitNL" : "G/L",
                    "unitEN" : "G/L",
                    "descriptionNL" : "gram per liter",
                    "descriptionEN" : "gram per litre"
                  }
                } ]
              },
              "toepassingen" : {
                "algemeen" : {
                  "gebruiksAanwijzing" : "Gebruiksaanwijzing",
                  "risicoBeperkendeMaatregelen" : "RisicoBeperkendemaatregel",
                  "effectenEnMaatregelen" : "effecten en maatregelen"
                },
                "toepassingen" : [ {
                  "naamVanGebruik" : "Arctische Flora",
                  "productSoort" : {
                    "id" : 10,
                    "code" : "PT01",
                    "descriptionNL" : "Biociden voor menselijke hygiëne",
                    "descriptionEN" : "Human hygiene (Disinfectants)"
                  },
                  "beschrijvingToegelatenGebruik" : "Dit is een beschrijving toegelaten gebruik",
                  "toepassingsGebieden" : [ {
                    "type" : "Binnenshuis",
                    "descriptionEN" : "Indoor",
                    "descriptionNL" : "Binnenshuis"
                  }, {
                    "type" : "Buitenshuis",
                    "descriptionEN" : "Outdoor or field use",
                    "descriptionNL" : "Buitenshuis"
                  } ],
                  "beschrijvingGebruiksGebied" : "beschrijvingGebruiksgebied",
                  "gebruikersCategorieen" : [ {
                    "type" : "AlgemeenPubliek",
                    "descriptionEN" : "Non-professional",
                    "descriptionNL" : "Algemeen Publiek",
                    "gebruik" : "NietProfessioneel"
                  }, {
                    "type" : "Professional",
                    "descriptionEN" : "Professional",
                    "descriptionNL" : "Professional",
                    "gebruik" : "Professioneel"
                  } ],
                  "doelOrganismen" : [ {
                    "id" : 13,
                    "descriptionNL" : "Acarid mites",
                    "descriptionEN" : "Acarid mites NL"
                  } ],
                  "toepassingsMethoden" : [ {
                    "methode" : {
                      "id" : 13,
                      "descriptionNL" : "Bait application",
                      "descriptionEN" : "Aas Applicatie"
                    },
                    "beschrijving" : "beschrijving",
                    "toepassingsDosering" : "toepassingsDosering",
                    "verdunning" : 1,
                    "toepassingsFrequentie" : "aantalTiming"
                  } ],
                  "gebruiksAanwijzing" : {
                    "specifiekeInstructies" : "specifieke instructies",
                    "risicoBeperkendeMaatregelen" : "risicoBeperkendemaatregelen",
                    "bijzonderheden" : "Bijzonderheden",
                    "verwijdering" : "verwijdering",
                    "voorwaarden" : "voorwaarden"
                  }
                } ]
              },
              "besluiten" : [ {
                "document" : {
                  "docId" : "doc-2",
                  "documentNaam" : "Bijlage.html"
                },
                "besluitType" : {
                  "id" : 15,
                  "descriptionNL" : "Bijlage",
                  "descriptionEN" : "Appendix",
                  "public" : true
                },
                "datumOndertekening" : "2016-08-02T08:46:41.675+02:00"
              }, {
                "document" : {
                  "docId" : "doc-1",
                  "documentNaam" : "Besluit.doc"
                },
                "besluitType" : {
                  "id" : 12,
                  "result" : "Accept",
                  "descriptionNL" : "Van rechtswege toelating",
                  "descriptionEN" : "Authorisation until EU-decision is implemented",
                  "public" : true
                },
                "datumOndertekening" : "2016-08-02T08:46:41.674+02:00"
              } ]
            }
        }


## Toelating Biocide [/public-api/1.0/toelatingen/22222]

Apiary ondersteunt nog geen conditionele responses. Dwz dat het niet mogelijk is om op basis van een middel-id verschillende toelating types (Biocides/Gewas/ToevoegingsStof) op te vragen.

Een workaround is het toevoegen van een additionele resource, hier toelating met middel-id 22222. Deze retourneerd vervolgens de toelating van een *Biocide*.

### Opvragen Toelating Biocide [GET]        

+ Response 200 (application/json)

         {
          "data": {
              "id" : "7544cbc1eff64f79a5185a7f4afca547",
              "naam" : "Wizard",
              "categorieType" : "Biocide",
              "gebruiker" : "Professioneel",
              "toelatingHouder" : {
                "companyName" : "BAYER",
                "address" : {
                  "street" : "Bayernslaan",
                  "number" : "888",
                  "postalcode" : "5635 AE",
                  "city" : "Ede",
                  "country" : "England"
                }
              },
              "toelating" : {
                "toelatingNummer" : {
                  "nl" : 121212,
                  "eu" : "EU-1234-9999-000",
                  "ingangsDatum" : "2016-08-02T08:46:41.662+02:00"
                },
                "expiratieDatum" : "2019-08-02T08:46:41.663+02:00",
                "opgebruikTermijn" : "2018-08-02T08:46:41.663+02:00",
                "afleverTermijn" : "2019-08-02T08:46:41.663+02:00",
                "gebruiksvoorschriften" : [ {
                  "gebruiker" : "Professioneel",
                  "documenten" : [ {
                    "document" : {
                      "docId" : "doc-1",
                      "documentNaam" : "Besluit.doc"
                    },
                    "ingangsDatum" : "2016-08-02T08:46:41.675+02:00",
                    "expiratieDatum" : "2019-08-02T08:46:41.663+02:00"
                  } ]
                } ]
              },
              "samenstellingen" : {
                "formuleringType" : {
                  "id" : 1,
                  "code" : "AE",
                  "descriptionNL" : "Aerosol spuitbus",
                  "descriptionEN" : "Aerosol dispenser"
                },
                "stoffen" : [ {
                  "stof" : {
                    "id" : 19,
                    "naamNL" : "acefaat",
                    "naamEN" : "acephate",
                    "ecNummer" : "250-241-2",
                    "casNummer" : "30560-19-1"
                  },
                  "functie" : {
                    "id" : 40,
                    "descriptionNL" : "Werkzame stof",
                    "descriptionEN" : "Active Ingredient"
                  },
                  "gehalte" : "456",
                  "concentratie" : {
                    "id" : 20,
                    "unitNL" : "G/L",
                    "unitEN" : "G/L",
                    "descriptionNL" : "gram per liter",
                    "descriptionEN" : "gram per litre"
                  }
                } ]
              },
              "toepassingen" : {
                "algemeen" : {
                  "gebruiksAanwijzing" : "Gebruiksaanwijzing",
                  "risicoBeperkendeMaatregelen" : "RisicoBeperkendemaatregel",
                  "effectenEnMaatregelen" : "effecten en maatregelen"
                },
                "toepassingen" : [ {
                  "naamVanGebruik" : "Arctische Flora",
                  "productSoort" : {
                    "id" : 10,
                    "code" : "PT01",
                    "descriptionNL" : "Biociden voor menselijke hygiëne",
                    "descriptionEN" : "Human hygiene (Disinfectants)"
                  },
                  "beschrijvingToegelatenGebruik" : "Dit is een beschrijving toegelaten gebruik",
                  "toepassingsGebieden" : [ {
                    "type" : "Binnenshuis",
                    "descriptionEN" : "Indoor",
                    "descriptionNL" : "Binnenshuis"
                  }, {
                    "type" : "Buitenshuis",
                    "descriptionEN" : "Outdoor or field use",
                    "descriptionNL" : "Buitenshuis"
                  } ],
                  "beschrijvingGebruiksGebied" : "beschrijvingGebruiksgebied",
                  "gebruikersCategorieen" : [ {
                    "type" : "AlgemeenPubliek",
                    "descriptionEN" : "Non-professional",
                    "descriptionNL" : "Algemeen Publiek",
                    "gebruik" : "NietProfessioneel"
                  }, {
                    "type" : "Professional",
                    "descriptionEN" : "Professional",
                    "descriptionNL" : "Professional",
                    "gebruik" : "Professioneel"
                  } ],
                  "doelOrganismen" : [ {
                    "id" : 13,
                    "descriptionNL" : "Acarid mites",
                    "descriptionEN" : "Acarid mites NL"
                  } ],
                  "toepassingsMethoden" : [ {
                    "methode" : {
                      "id" : 13,
                      "descriptionNL" : "Bait application",
                      "descriptionEN" : "Aas Applicatie"
                    },
                    "beschrijving" : "beschrijving",
                    "toepassingsDosering" : "toepassingsDosering",
                    "verdunning" : 1,
                    "toepassingsFrequentie" : "aantalTiming"
                  } ],
                  "gebruiksAanwijzing" : {
                    "specifiekeInstructies" : "specifieke instructies",
                    "risicoBeperkendeMaatregelen" : "risicoBeperkendemaatregelen",
                    "bijzonderheden" : "Bijzonderheden",
                    "verwijdering" : "verwijdering",
                    "voorwaarden" : "voorwaarden"
                  }
                } ]
              },
              "besluiten" : [ {
                "document" : {
                  "docId" : "doc-2",
                  "documentNaam" : "Bijlage.html"
                },
                "besluitType" : {
                  "id" : 15,
                  "descriptionNL" : "Bijlage",
                  "descriptionEN" : "Appendix",
                  "public" : true
                },
                "datumOndertekening" : "2016-08-02T08:46:41.675+02:00"
              }, {
                "document" : {
                  "docId" : "doc-1",
                  "documentNaam" : "Besluit.doc"
                },
                "besluitType" : {
                  "id" : 12,
                  "result" : "Accept",
                  "descriptionNL" : "Van rechtswege toelating",
                  "descriptionEN" : "Authorisation until EU-decision is implemented",
                  "public" : true
                },
                "datumOndertekening" : "2016-08-02T08:46:41.674+02:00"
              } ]
            }
        }


## Toelating Gewas [/public-api/1.0/toelatingen/55555]

Apiary ondersteunt nog geen conditionele responses. Dwz dat het niet mogelijk is om op basis van een middel-id verschillende toelating types (Biocides/Gewas/ToevoegingsStof) op te vragen.

Een workaround is het toevoegen van een additionele resource, hier toelating met middel-id 55555. Deze retourneerd vervolgens de toelating van een *Gewasbeschermingsmiddel*.

### Opvragen Toelating Gewas [GET]        
        
+ Response 200 (application/json)

        {
          "data": {
            "id": "55555",
            "naam": "TRIFOCIDE VLOEIBAAR DNOC",
            "categorieType": "Gewas",
            "gebruiker": "Beide",
            "toelatingHouder": {
              "id": "234232332d",
              "companyName": "Techno Trading Holland",
              "address": {
                "street": "Groesweg",
                "number": "13",
                "postalcode": "5993 NN",
                "city": "Maasbree",
                "country": "Nederland"
              }
            },
            "toelating": {
              "toelatingNummer": {
                "nl": 3204,
                "eu": "NL-0005643-0000",
                "ingangsDatum": "2016-01-21T00:00:00.000+01:00"
              },
              "expiratieDatum": "2016-01-18T00:00:00.000+01:00",
              "actueel": [
                {
                  "gebruiker": "NietProfessioneel",
                  "wCode": "W3",
                  "gebruiksvoorschrift": {
                    "document": {
                      "docId": "doc-1",
                      "documentNaam": "Gebruiksvoorschrift.doc"
                    },
                    "ingangsDatum": "2016-01-21T00:00:00.000+01:00",
                    "expiratieDatum": "2016-01-18T00:00:00.000+01:00"
                  }
                },
                {
                  "gebruiker": "Professioneel",
                  "wCode": "W1",
                  "gebruiksvoorschrift": {
                    "document": {
                      "docId": "doc-1",
                      "documentNaam": "Gebruiksvoorschrift.doc"
                    },
                    "ingangsDatum": "2016-01-21T00:00:00.000+01:00",
                    "expiratieDatum": "2016-01-18T00:00:00.000+01:00"
                  }
                }
              ],
              "voorgaand": [
                {
                  "gebruiker": "NietProfessioneel",
                  "wCoderingen": [
                    {
                      "wCode": "W2",
                      "gebruiksvoorschrift": {
                        "document": {
                          "docId": "doc-1",
                          "documentNaam": "Gebruiksvoorschrift.doc"
                        },
                        "ingangsDatum": "2016-01-21T00:00:00.000+01:00",
                        "expiratieDatum": "2016-01-18T00:00:00.000+01:00"
                      },
                      "expiratieDatum": "2016-01-18T00:00:00.000+01:00",
                      "opgebruikTermijn": "2016-01-17T00:00:00.000+01:00",
                      "afleverTermijn": "2016-01-16T00:00:00.000+01:00"
                    },
                    {
                      "wCode": "W1",
                      "gebruiksvoorschrift": {
                        "document": {
                          "docId": "doc-1",
                          "documentNaam": "Gebruiksvoorschrift.doc"
                        },
                        "ingangsDatum": "2016-01-21T00:00:00.000+01:00",
                        "expiratieDatum": "2016-01-18T00:00:00.000+01:00"
                      },
                      "expiratieDatum": "2016-01-18T00:00:00.000+01:00",
                      "opgebruikTermijn": "2016-01-17T00:00:00.000+01:00",
                      "afleverTermijn": "2016-01-16T00:00:00.000+01:00"
                    },
                    {
                      "gebruiksvoorschrift": {
                        "document": {
                          "docId": "doc-1",
                          "documentNaam": "Gebruiksvoorschrift.doc"
                        },
                        "ingangsDatum": "2016-01-21T00:00:00.000+01:00",
                        "expiratieDatum": "2016-01-18T00:00:00.000+01:00"
                      },
                      "expiratieDatum": "2016-01-18T00:00:00.000+01:00",
                      "opgebruikTermijn": "2016-01-17T00:00:00.000+01:00",
                      "afleverTermijn": "2016-01-16T00:00:00.000+01:00"
                    }
                  ]
                },
                {
                  "gebruiker": "Professioneel",
                  "wCoderingen": [
                    {
                      "gebruiksvoorschrift": {
                        "document": {
                          "docId": "doc-1",
                          "documentNaam": "Gebruiksvoorschrift.doc"
                        },
                        "ingangsDatum": "2016-01-21T00:00:00.000+01:00",
                        "expiratieDatum": "2016-01-18T00:00:00.000+01:00"
                      },
                      "expiratieDatum": "2016-01-18T00:00:00.000+01:00",
                      "opgebruikTermijn": "2016-01-17T00:00:00.000+01:00",
                      "afleverTermijn": "2016-01-16T00:00:00.000+01:00"
                    }
                  ]
                }
              ]
            },
            "toepassingen": [
              {
                "id": "1337",
                "naamVanGebruik": "Herbiciden",
                "geclaimdOrganisme": "Geclaimd organisme",
                "toepassingsLocaties": [
                  {
                    "id": 1,
                    "descriptionNL": "Bedekt",
                    "descriptionEN": "Covered"
                  },
                  {
                    "id": 2,
                    "descriptionNL": "Onbedekt",
                    "descriptionEN": "Uncovered"
                  }
                ],
                "dtgLijstVersion": "2.1",
                "toepassingsGebieden": [
                  {
                    "groepNL": "Fruitgewassen",
                    "groepEN": "Fruit crops",
                    "items": [
                      {
                        "groepNL": "Groot fruit",
                        "groepEN": "Large fruits",
                        "items": [
                          {
                            "groepNL": "Pitvruchten",
                            "groepEN": "Pome fruit",
                            "items": [
                              {
                                "gewasNL": "Appel",
                                "gewasEN": "Apple",
                                "eppo": "MABSD",
                                "bijaantrekkelijk": true,
                                "teeltOnbedektJaar": "1"
                              },
                              {
                                "gewasNL": "Peer",
                                "gewasEN": "Pear",
                                "eppo": "PYUCO, PYUPC",
                                "opmerkingenNL": "Incl. Japanse peer",
                                "opmerkingenEN": "Including Oriental pear",
                                "bijaantrekkelijk": true,
                                "teeltOnbedektJaar": "1"
                              }
                            ]
                          }
                        ]
                      },
                      {
                        "groepNL": "Kleinfruit",
                        "groepEN": "Small fruits",
                        "items": [
                          {
                            "groepNL": "Aardbei",
                            "groepEN": "Strawberries",
                            "beperktTotNL": "wilde Aardbei",
                            "beperktTotEN": "wild Strawberries",
                            "eppo": "FRAAN",
                            "bijenopmerkingNL": "Op het moment dat bloei plaatsvindt",
                            "bijenopmerkingEN": "When flowering occurs",
                            "bijaantrekkelijk": true,
                            "teeltOnbedektJaar": "1",
                            "teeltBedektJaar": "1 - 2",
                            "items": []
                          }
                        ]
                      }
                    ]
                  },
                  {
                    "groepNL": "Steenvruchten",
                    "groepEN": "Stone fruit",
                    "items": [
                      {
                        "gewasNL": "Kers",
                        "gewasEN": "Cherry",
                        "beperktTotNL": "rode Kers",
                        "beperktTotEN": "red Cherry",
                        "eppo": "PRNAV, PRNCE",
                        "opmerkingenNL": "Zoete kers\nZure kers",
                        "opmerkingenEN": "Sweet cherry\nSour cherry",
                        "bijaantrekkelijk": true,
                        "teeltOnbedektJaar": "1",
                        "teeltBedektJaar": "1"
                      }
                    ]
                  }
                ]
              },
              {
                "id": "1340",
                "naamVanGebruik": "Besproeing",
                "geclaimdOrganisme": "Geclaimd organisme",
                "dtgLijstVersion": "2.1",
                "toepassingsGebieden": [
                  {
                    "groepNL": "Peulgroenten",
                    "groepEN": "Peulgroenten",
                    "items": [
                      {
                        "groepNL": "Boon met peul",
                        "groepEN": "Boon met peul",
                        "items": [
                          {
                            "gewasNL": "Stamslaboon",
                            "gewasEN": "Stamslaboon",
                            "eppo": "PHSVN",
                            "opmerkingenNL": "sperzieboon, boterboon\nwasboon",
                            "opmerkingenEN": "sperzieboon, boterboon\nwasboon"
                          }
                        ]
                      }
                    ]
                  }
                ]
              }
            ],
            "samenstellingen": {
              "formuleringType": {
                "id": 72,
                "code": "RB",
                "descriptionNL": "Lokmiddel (klaar voor gebruik)",
                "descriptionEN": "Bait (ready for use)"
              },
              "stoffen": [
                {
                  "stof": {
                    "id": 11287,
                    "naamNL": "(2-butoxyethoxy)azijnzuur",
                    "naamEN": "(2-butoxyethoxy)acetic acid",
                    "casNummer": "82941-26-2"
                  },
                  "functie": {
                    "id": 5,
                    "descriptionNL": "Werkzame stof",
                    "descriptionEN": "Active substance"
                  },
                  "gehalte": "12",
                  "concentratie": {
                    "id": 2,
                    "unitNL": "%V/V",
                    "unitEN": "%V/V",
                    "descriptionNL": "volumeprocent",
                    "descriptionEN": "volumeprocent"
                  }
                },
                {
                  "stof": {
                    "id": 11287,
                    "naamNL": "(2-butoxyethoxy)azijnzuur",
                    "naamEN": "(2-butoxyethoxy)acetic acid",
                    "casNummer": "82941-26-2"
                  },
                  "functie": {
                    "id": 6,
                    "descriptionNL": "Beschermstof",
                    "descriptionEN": "Protective substance"
                  },
                  "gehalte": "1",
                  "concentratie": {
                    "id": 4,
                    "unitNL": "CFU/G",
                    "unitEN": "CFU/G",
                    "descriptionNL": "kolonievormende sporen per gram",
                    "descriptionEN": "kolonievormende sporen per gram"
                  }
                }
              ]
            },
            "besluiten": [
              {
                "documentNaam": "ExternalBesluit.doc",
                "besluitType": {
                  "id": 563,
                  "result": "Accept",
                  "descriptionNL": "Uitbreiding toelating",
                  "descriptionEN": "Extention of an authorisation"
                },
                "datumOndertekening": "2016-01-21T00:00:00.000+01:00"
              },
              {
                "documentNaam": "Bijlage.doc",
                "besluitType": {
                  "id": 700,
                  "descriptionNL": "Actueel gebruiksvoorschrift",
                  "descriptionEN": ""
                },
                "datumOndertekening": "2016-01-21T00:00:00.000+01:00"
              }
            ]
          }
        }


## Toelating ToevoegingsStof [/public-api/1.0/toelatingen/88888]

Apiary ondersteunt nog geen conditionele responses. Dwz dat het niet mogelijk is om op basis van een middel-id verschillende toelating types (Biocides/Gewas/ToevoegingsStof) op te vragen.

Een workaround is het toevoegen van een additionele resource, hier toelating met middel-id 88888. Deze retourneerd vervolgens de toelating van een *Toevoeingsstof*.

### Opvragen Toelating Toevoegingsstof [GET]        
        
+ Response 200 (application/json)

            {
                "data": {
                  "id" : "88888",
                  "naam": "ACTIROB B",
                  "categorieType": "ToevoegingsStof",
                  "gebruik": "Professioneel",
                  "toelatingHouder": {
                    "id":"2323asdfsdf32", 
                    "companyName": "FA. S. V.D. WERF",
                    "address": {
                      "street": "Cartografenweg",
                      "number": "34",
                      "postalcode": "5141 MT",
                      "city": "Waalwijk",
                      "country": "Nederland"
                    }
                  },
                  "toelating": {
                    "toelatingNummer": {
                      "nl": 343421,
                      "ingangsDatum": "2016-01-21T00:00:00.000+01:00"
                    },
                    "expiratieDatum": "2016-01-18T00:00:00.000+01:00"
                  },
                  "besluiten": [
                    {
                      "documentNaam": "ExternalBesluit.doc",
                      "besluitType": {
                        "id": 563,
                        "result": "Accept",
                        "descriptionNL": "Uitbreiding toelating",
                        "descriptionEN": "Extention of an authorisation"
                      },
                      "datumOndertekening": "2016-01-21T00:00:00.000+01:00"
                    },
                    {
                      "documentNaam": "Bijlage.doc",
                      "besluitType": {
                        "id": 700,
                        "descriptionNL": "Actueel gebruiksvoorschrift",
                        "descriptionEN": ""
                      },
                      "datumOndertekening": "2016-01-21T00:00:00.000+01:00"
                    }
                  ]
                }
            }
            
            

## Stamdata Toelatingnummers - NOT USED [/public-api/1.0/stamdata/toelatingnummers{?filter%5Bquery%5D,page%5Boffset%5D,page%5Blimit%5D}]

Met deze service kunnen toelating nummers opgezocht worden. Deze service ondersteunt paginatie.

+ Parameters
    + filter%5Bquery%5D: 421 (string, optional) - query parameter met een deel van het toelating nummer van het middel (nl of eu). In de zoekvraag wordt dit vertaald naar `contains query`, niet hoofdlettergevoelig
    + page%5Boffset%5D (number, optional) -  aantal toelatingnummers die overgeslagen worden voordat het resultaat geretourneerd wordt
        + Default: `0`
    + page%5Blimit%5D (number, optional) - aantal te retourneren toelatingnummers  
        + Default: `100`


### Opvragen Toelatingnummers [GET]

+ Response 200 (application/json)

        {
            "meta": {
                "total": 1255,
                "offset":0,
                "limit":100
            },
            "data": ["234211", "23421", "421663", "NL-0003421-0000"]
            }

            
## Stamdata Stoffen [/public-api/1.0/stamdata/stoffen{?filter%5Bfunctie%5D,filter%5Bquery%5D,filter%5Blang%5D,page%5Boffset%5D,page%5Blimit%5D}]

Met deze service kunnen stoffen opgezocht worden. Deze service ondersteunt paginatie.  

+ Parameters
    + filter%5Bfunctie%5D (enum[functie], required) - de functie van de stof. Meerdere functies  worden in de zoekvraag vertaald naar: `OR`. 
        + Members
            + `WerkzameStof`
            + `Beschermstof`
    + filter%5Bquery%5D: ben (string, required) - query parameter met een deel van een stof attribute zijnde, `naamNL`, `naamEN`, `ecNumme`r of `casNummer`. In de zoekvraag wordt dit vertaald naar: `naamNL`, `naamEN`, `ecNummer` of `casNummer` `contains query`, niet hoofdlettergevoelig
    + filter%5Blang%5D: nl (enum[lang], optional) - language parameter met de afkorting van de gewenste taal. Default is `nl`.
        + Members
                + `nl`
                + `en`
    + page%5Boffset%5D (number, optional) -  aantal stoffen die overgeslagen worden voordat het resultaat geretourneerd wordt
        + Default: `0`
    + page%5Blimit%5D (number, optional) - aantal te retourneren stoffen 
        + Default: `100`


### Opvragen Stoffen [GET]

+ Response 200 (application/json)

        {
            "meta": {
                "total": 734,
                "offset":0,
                "limit":100
            },
            "data": [
                {"naamEN":"(1-methylethyl)benzenesulfonic acid, sodium salt","naamNL":"(1-methylethyl)benzeensulfonzuur, natriumzout","casNummer":"28348-53-0","id":10601},
                {"ecNummer":"230-515-8","naamEN":"(2-bromo-2-nitroethenyl)benzene","naamNL":"(2-broom-2-nitrovinyl)benzeen","casNummer":"7166-19-0","id":6939},
                {"ecNummer":"244-445-0","naamEN":"(benzothiazol-2-ylthio)methyl thiocyanate","naamNL":"(benzothiazool-2-ylthio)methylthiocyanaat","casNummer":"21564-17-0","id":7218},
                {"ecNummer":"238-588-8","naamEN":"benzylhemiformal","naamNL":"(benzyloxy)methanol","casNummer":"14548-60-8","id":10022},
                {"ecNummer":"215-551-4","naamEN":"(dodecylbenzyl)trimethylammonium chloride","naamNL":"(dodecylbenzyl)trimethylammonium chloride","casNummer":"1330-85-4","id":2372}
                ]   
            }


## Stamdata Toelatinghouders [/public-api/1.0/stamdata/toelatinghouders{?filter%5Bnaam%5D,page%5Boffset%5D,page%5Blimit%5D}]

Met deze service kunnen toelatinghouders opgezocht worden. Deze service ondersteunt paginatie.

+ Parameters
    + filter%5Bnaam%5D: a (string, optional) -  naam van het bedrijf or een deel ervan. In de zoekvraag wordt dit vertaald naar `contains naam`, niet hoofdlettergevoelig
    + page%5Boffset%5D (number, optional) -  aantal toelatinghouders die overgeslagen worden voordat het resultaat geretourneerd wordt
        + Default: `0`
    + page%5Blimit%5D (number, optional) - aantal te retourneren toelatinghouders  
        + Default: `100`


### Opvragen Toelatinghouders [GET]

+ Response 200 (application/json)

        {
            "meta": {
                "total": 1255,
                "offset":0,
                "limit":100
            },
            "data": [
                {"id":"9384adf1212", "companyName" : "BAYER", "address" : {"street" : "Bayernslaan","number" : "888", "postalcode" : "5635 AE", "city" : "Ede", "country" : "England"}},
                {"id":"32323ad1213", "companyName":"Wacon Aquaven B.V.","address":{"street":"Noorderhaven","number":"100","postalcode":"8861 AR","city":"Harlingen","country":"Nederland"}},
                {"id":"12ddaerwe17", "companyName":"FA. S. V.D. WERF","address":{"street":"Cartografenweg","number":"34","postalcode":"5141 MT","city":"Waalwijk","country":"Nederland"}},
                {"id":"33434ss1230", "companyName":"Techno Trading Holland","address":{"street":"Groesweg","number":"13","postalcode":"5993 NN","city":"Maasbree","country":"Nederland"}}
            ]
        }
        
## Productcodes voor Biocides [/public-api/1.0/stamdata/biocide/productcodes{?filter%5Bquery%5D,filter%5Blang%5D,page%5Boffset%5D,page%5Blimit%5D}]

Met deze service kunnen productcodes (PT-Codes) voor Biocides opgezocht worden. Deze service ondersteunt paginatie.

+ Parameters
    + filter%5Bquery%5D: PT0 (string, optional) - query parameter met PT code, beschrijving een deel ervan. In de zoekvraag wordt dit vertaald naar `contains naam`, niet hoofdlettergevoelig
    + filter%5Blang%5D: nl (enum[lang], optional) - language parameter met de afkorting van de gewenste taal. Default is `nl`.
        + Members
                + `nl`
                + `en`
    + page%5Boffset%5D (number, optional) -  aantal productcodes die overgeslagen worden voordat het resultaat geretourneerd wordt
        + Default: `0`
    + page%5Blimit%5D (number, optional) - aantal te retourneren productcodes  
        + Default: `100`


### Opvragen Procutcodes voor Biocides [GET]

+ Response 200 (application/json)

        {
            "meta": {
                "total": 1255,
                "offset":0,
                "limit":100
            },
            "data": [{
                  "id" : 1,
                  "code" : "PT01",
                  "descriptionNL" : "Biociden voor menselijke hygiëne",
                  "descriptionEN" : "Human hygiene biocidal products",
                  "echaCode" : "PT01"
                }, {
                  "id" : 2,
                  "code" : "PT02",
                  "descriptionNL" : "Desinfecterende middelen voor privé-gebruik en voor de openbare gezondheidszorg, alsmede andere desinfectantia",
                  "descriptionEN" : "Private area and public health area disinfectants and other biocidal products",
                  "echaCode" : "PT02"
                }, {
                  "id" : 3,
                  "code" : "PT03",
                  "descriptionNL" : "Biociden voor veterinaire hygiëne-doeleinden",
                  "descriptionEN" : "Veterinary hygiene biocidal products",
                  "echaCode" : "PT03"
                }]
        }

        
## Doelorganismen voor Biocides [/public-api/1.0/stamdata/biocide/doelorganismen{?filter%5Bquery%5D,filter%5Blang%5D,page%5Boffset%5D,page%5Blimit%5D}]

Met deze service kunnen triviale namen van doelorganismen voor Biocides opgezocht worden. Deze service ondersteunt paginatie.

+ Parameters
    + filter%5Bquery%5D: Acarid (string, optional) - query parameter met een triviale organisme naam of een deel ervan. In de zoekvraag wordt dit vertaald naar `contains naam`, niet hoofdlettergevoelig
    + filter%5Blang%5D: nl (enum[lang], optional) - language parameter met de afkorting van de gewenste taal. Default is `nl`.
        + Members
                + `nl`
                + `en`
    + page%5Boffset%5D (number, optional) -  aantal doelorganismen die overgeslagen worden voordat het resultaat geretourneerd wordt
        + Default: `0`
    + page%5Blimit%5D (number, optional) - aantal te retourneren doelorganismen  
        + Default: `100`


### Opvragen Doelorganismen voor Biocides [GET]

+ Response 200 (application/json)

        {
            "meta": {
                "total": 1255,
                "offset":0,
                "limit":100
            },
            "data": [
                {"id": 1, "echaCode": "4998", "descriptionNL": "Acarid mites", "descriptionEN": "Acarid mites"},
                {"id": 205, "descriptionNL": "Adults | Ants","descriptionEN": "Adults | Ants"},
                {"id": 2, "echaCode": "4999", "descriptionNL": "Aedes mosquitoes","descriptionEN": "Aedes mosquitoes"},
                {"id": 3, "echaCode": "5794", "descriptionNL": "Algae","descriptionEN": "Algae"}
              ]
        }        
        
## Doelorganismen voor Gewasbeschermingsmiddelen [/public-api/1.0/stamdata/gewas/doelorganismen{?filter%5Bquery%5D,filter%5Blang%5D,page%5Boffset%5D,page%5Blimit%5D}]

Met deze service kunnen doelorganismen van gewasbeschermingsmiddelen opgevraagd worden. Deze service ondersteunt paginatie.

+ Parameters
    + filter%5Bquery%5D: ar (string, optional) - query parameter met doelorganisme of een deel ervan. In de zoekvraag wordt dit vertaald naar `contains naam`, niet hoofdlettergevoelig
    + filter%5Blang%5D: nl (enum[lang], optional) - language parameter met de afkorting van de gewenste taal. Default is `nl`.
        + Members
                + `nl`
                + `en`
    + page%5Boffset%5D (number, optional) -  aantal gewassen die overgeslagen worden voordat het resultaat geretourneerd wordt
        + Default: `0`
    + page%5Blimit%5D (number, optional) - aantal te retourneren gewassen  
        + Default: `100`
    

### Opvragen Doelorganismen voor Gewasbeschermingsmiddelen [GET]

+ Response 200 (application/json)

        {
            "meta": {
                "total": 1255,
                "offset":0,
                "limit":100
            },
            "data": [
                    {"id": 1, "descriptionNL": "TBD-nl-1", "descriptionEN": "TBD-en-1"},
                    {"id": 2, "descriptionNL": "TBD-nl-2", "descriptionEN": "BD-en-2"}
                ]
        }
        

## Toepassingsgebieden voor Gewasbeschermingsmiddelen [/public-api/1.0/stamdata/gewas/toepassingsgebieden{?filter%5Bquery%5D,filter%5Blang%5D,page%5Boffset%5D,page%5Blimit%5D}]

Met deze service kunnen toepassingsgebieden van gewasbeschermingsmiddelen gebaseerd op Definitielijsten Toepassingsgebieden Gewasbeschermingsmiddelen (DTG) opgevraagd worden. Deze service ondersteunt paginatie.

+ Parameters
    + filter%5Bquery%5D: ar (string, optional) - query parameter met gewas of eppo code of een deel ervan. In de zoekvraag wordt dit vertaald naar `contains naam`, niet hoofdlettergevoelig
    + filter%5Blang%5D: nl (enum[lang], optional) - language parameter met de afkorting van de gewenste taal. Default is `nl`.
        + Members
                + `nl`
                + `en`
    + page%5Boffset%5D (number, optional) -  aantal gewassen die overgeslagen worden voordat het resultaat geretourneerd wordt
        + Default: `0`
    + page%5Blimit%5D (number, optional) - aantal te retourneren gewassen  
        + Default: `100`
    
    

### Opvragen Toepassingsgebieden voor Gewasbeschermingsmiddelen [GET]

+ Response 200 (application/json)

        {
            "meta": {
                "total": 1255,
                "offset":0,
                "limit":100
            },
            "data": [{
                "naamNL": "Aardpeer",
                "naamEN": "Jerusalem artichoke",
                "type": "gewas",
                "eppo": "HELTU"
              },
              {
                "naamNL": "Japanse aardappel",
                "naamEN": "Japanese artichoke",
                "type": "gewas",
                "eppo": "STASB"
              },
              {
                "naamNL": "Knoflook",
                "naamEN": "Garlic",
                "type": "subgroep",
                "eppo": "STASB"
              },
              {
                "naamNL": "Akkerbouwgewassen",
                "naamEN": "Arable crops",
                "type": "groep",
                "eppo": "STASB"
              }
            ]
        }                
        
        
## Toepassingslocaties voor Gewasbeschermingsmiddelen [/public-api/1.0/stamdata/gewas/toepassingslocaties{?filter%5Bquery%5D,filter%5Blang%5D,page%5Boffset%5D,page%5Blimit%5D}]

Met deze service kunnen toepassingslocaties voor Gewasbeschermingsmiddelen opgezocht worden. Deze service ondersteunt paginatie.

+ Parameters
    + filter%5Bquery%5D: Bede (string, required) - query parameter met een toepassingslocatie of een deel ervan. In de zoekvraag wordt dit vertaald naar `contains naam`, niet hoofdlettergevoelig
    + filter%5Blang%5D: nl (enum[lang], optional) - language parameter met de afkorting van de gewenste taal. Default is `nl`.
        + Members
                + `nl`
                + `en`
    + page%5Boffset%5D (number, optional) -  aantal toepassingslocaties die overgeslagen worden voordat het resultaat geretourneerd wordt
        + Default: `0`
    + page%5Blimit%5D (number, optional) - aantal te retourneren toepassingslocaties  
        + Default: `100`


### Opvragen Toepassingslocaties voor Gewasbeschermingsmiddelen [GET]        

+ Response 200 (application/json)

        {
            "meta": {
                "total": 1255,
                "offset":0,
                "limit":100
            },
            "data": [
                    {"id": 1, "descriptionNL": "Bedekt", "descriptionEN": "Covered"},
                    {"id": 2, "descriptionNL": "Onbedekt", "descriptionEN": "Uncovered"}
                ]
        }
        
        
        
        
## Aard Werking voor Gewasbeschermingsmiddelen [/public-api/1.0/stamdata/gewas/aardwerkingen{?filter%5Bquery%5D,filter%5Blang%5D,page%5Boffset%5D,page%5Blimit%5D}]

Met deze service kunnen aard werkingen voor Gewasbeschermingsmiddelen opgezocht worden. Deze service ondersteunt paginatie.

+ Parameters
    + filter%5Bquery%5D: Bede (string, required) - query parameter met aard werking of een deel ervan. In de zoekvraag wordt dit vertaald naar `contains naam`, niet hoofdlettergevoelig
    + filter%5Blang%5D: nl (enum[lang], optional) - language parameter met de afkorting van de gewenste taal. Default is `nl`.
        + Members
                + `nl`
                + `en`
    + page%5Boffset%5D (number, optional) -  aantal aard werkingen die overgeslagen worden voordat het resultaat geretourneerd wordt
        + Default: `0`
    + page%5Blimit%5D (number, optional) - aantal te retourneren aard werkingen  
        + Default: `100`


### Opvragen Aard Werking voor Gewasbeschermingsmiddelen [GET]        

+ Response 200 (application/json)

        {
            "meta": {
                "total": 1255,
                "offset":0,
                "limit":100
            },
            "data": [
                    {"id": 1, "descriptionNL": "Werking-1", "descriptionEN": "Type-of-use-1"},
                    {"id": 2, "descriptionNL": "Werking-2", "descriptionEN": "Type-of-use-2"}
                ]
        }