FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# MST Public API

De MST public API faciliteert het doorzoeken en opvragen van toegelaten biocides, gewasbeschermingsmiddelen en toevoegingsstoffen.

Deze API maakt gebruik van de [jsonapi](http://jsonapi.org/recommendations/) standaard.

[jsonapi](http://jsonapi.org/recommendations/) maakt voor zommige query parameters gebruik van een typering. B.v. het type `filter` gevolgd door `[` veldnaam `]`.
De hier gebruikte types zijn:
- Filteren: `filter[veldNaam]`
- Paginatie: `page[offset]` en `page[limit]`. Deze parameters dienen samen gebruikt te worden. B.v. `/toelatingen?page[offset]=100&page[limit]=25` slaat de toelatingen 0-100 over and retourneert 101-125

**Belangrijk**

Omdat in query parameters blokhaken (`[]`) niet toegestaan zijn dienen deze url-encode te worden.
Dit betekent dat b.v. `filter[fieldName]` vertaald dient te worden naar: `filter%5BfieldName%5D`

## Authorisations summary [/public-api/1.0/authorisations{?filter%5Blocale%5D,filter%5BproductName%5D,filter%5BproductStatus%5D,filter%5BcategoryType%5D,filter%5BregistrationNumber%5D,filter%5BuserType%5D,filter%5BactiveSubstances%5D,filter%5BsafenerSubstances%5D,filter%5BauthorisationHolders%5D,filter%5BbiocideProductcodes%5D,filter%5BbiocideTargetOrganisms%5D,filter%5BbiocideTargetInfo%5D,filter%5BpppTargetCrops%5D,filter%5BpppTargetOrganisms%5D,filter%5BpppTargetlocations%5D,filter%5BpppOutcomeTypes%5D,filter%5BexpirationDateFrom%5D,filter%5BexpirationDateTo%5D,filter%5BlastRenewalDateFrom%5D,filter%5BlastRenewalDateTot%5D,sort,page%5Boffset%5D,page%5Blimit%5D}]

Met deze service kunnen authorisations op basis van een groot aantal parameters doorzocht worden. Daarnaast biedt deze service sortering en paginatie.
Meerdere filters worden in de zoekvraag vertaald naar `AND`. Uitzondering is `filter%5BproductName%5D` en `filter%5BregistrationNumber%5D`. Deze worden vertaald naar `OR`.
Dates worden in het volgende ISO format teruggegeven: `yyyy-MM-ddTHH:mm:ss.SSSZ`.

+ Parameters
    + filter%5Blocale%5D: nl (enum[locale], optional) - locale parameter voor targetCrops met de afkorting van de gewenste taal. Per default `nl` and `en` is returned.
        + Members
                + `nl`
                + `en`
    + filter%5BproductStatus%5D (enum%5BproductStatus%5D, optional) - de status van een product.
        + Members
            + `Valid`
            + `Expired`
    + filter%5BcategoryType%5D (enum%5BcategoryType%5D, optional) - het categorie type van een product.
        + Members
            + `Biocide`
            + `PPP`
            + `Adjuvant`
    + filter%5BproductName%5D (string, optional) - de naam van het product of een deel ervan.  In de zoekvraag wordt dit vertaald naar `contains naam,` niet hoofdlettergevoelig. De filters `filter%5BproductName%5D` en `filter%5BregistrationNumber%5D` worden in de zoekvraag vertaald naar `OR`.
    + filter%5BregistrationNumber%5D (string, optional) - het authorisation nummer van het product, nl of eu. De filters `filter%5BproductName%5D` en `filter%5BregistrationNumber%5D` worden in de zoekvraag vertaald naar `OR`.
    + filter%5BuserType%5D (enum%5BuserType%5D, optional) - de userType van een product.
        + Members
            + `Professional`
            + `NonProfessional`
            + `Both`
    + filter%5BactiveSubstances%5D (number, optional) - id's van activesubstances, koma separated. Meerdere id's worden in de zoekvraag vertaald naar: `OR`.
    + filter%5BsafenerSubstances%5D (number, optional) - id's van safenersubstances, koma separated. Meerdere id's worden in de zoekvraag vertaald naar: `OR`.
    + filter%5BauthorisationHolders%5D (string, optional) - id's van authorisationholders, koma separated. Meerdere id's worden in de zoekvraag vertaald naar: `OR`.
    + filter%5BbiocideProductcodes%5D (number, optional) - id's van productcodes, koma separated. Meerdere id's worden in de zoekvraag vertaald naar: `OR`.
    + filter%5BbiocideTargetOrganisms%5D (number, optional) - id's van triviale targetOrganism namen, koma separated. Meerdere id's worden in de zoekvraag vertaald naar: `OR`.
    + filter%5BbiocideTargetInfo%5D (string, optional) - vrije tekst die zoekt in de uses informatie van biocides.
    + filter%5BpppTargetOrganisms%5D (number, optional) - id's van targetOrganisms, koma separated. Meerdere id's worden in de zoekvraag vertaald naar: `OR`.
    + filter%5BpppTargetCrops%5D (string, optional) - namen van PPPs gevolgd door locatie in de DTG hierarchie zijnde `groep, subgroep, gewas, eppo` of engels: `group, subgroup, plant, eppo`, geconcateneerd met `::`. Meerdere paden worden koma separated, deze worden in de zoekvraag vertaald naar: `OR`. Voorbeeld: targetcrops voor een PPP voor `Appel`, `Steenvruchten` of `ISTAC`: `Appel::gewas,Steenvruchten::subgroep,ISTAC::eppo`.
    + filter%5BpppTargetlocations%5D (number, optional) - id's van targetlocations, koma separated. Meerdere id's worden in de zoekvraag vertaald naar: `OR`.
    + filter%5BpppOutcomeTypes%5D (number, optional) - id's van aard werkingen, koma separated. Meerdere id's worden in de zoekvraag vertaald naar: `OR`.
    + filter%5BexpirationDateFrom%5D (string, optional) - expiratie datum vanaf, in ISO formaat: b.v. `yyyy-MM-ddTHH:mm:ssZ`. `yyyy-MM-dd` is ook mogelijk en vertaald zich naar: `yyyy-MM-ddT00:00:00Z`
    + filter%5BexpirationDateTo%5D (string, optional) - expiratie datum tot en met in ISO formaat: b.v. `yyyy-MM-ddTHH:mm:ssZ`. `yyyy-MM-dd` is ook mogelijk en vertaald zich naar: `yyyy-MM-ddT00:00:00Z`
    + filter%5BlastRenewalDateFrom%5D (string, optional) - datum ondertekening vanaf in ISO formaat: b.v. `yyyy-MM-ddTHH:mm:ssZ`. `yyyy-MM-dd` is ook mogelijk en vertaald zich naar: `yyyy-MM-ddT00:00:00Z`
    + filter%5BlastRenewalDateTot%5D (string, optional) - datum ondertekening tot en met in ISO formaat: b.v. `yyyy-MM-ddTHH:mm:ssZ`. `yyyy-MM-dd` is ook mogelijk en vertaald zich naar: `yyyy-MM-ddT00:00:00Z`
    + sort (string optional) - koma separated lijst van veldnamen waarop gesorteerd dient te worden. Default is de sortering _oplopend_. Door een '`-`' aan de veldnaam toe te voegen is de sortering _aflopend_. B.v. `sort=productName,-lastRenewalDate`.
        Er kunnen op de volgende velden gesorteerd worden: `productName`, `categoryType`, `registrationNumber`, `expirationDate`, `lastRenewalDate`
    + page%5Boffset%5D (number, optional) -  aantal authorisations die overgeslagen worden voordat het resultaat geretourneerd wordt
        + Default: `0`
    + page%5Blimit%5D (number, optional) - aantal te retourneren authorisations
        + Default: `50`

### Request Authorisations [GET]

+ Response 200 (application/json)

            {
               "meta": {
                "total": 1255,
                "offset":0,
                "limit":50
            },
            "data": [
              {
                "id" : "23456",
                "name": "Mirazyl",
                "categoryType": "Biocide",
                "registrationNumber": "NL-0006252-0000",
                "expirationDate": "2019-02-10T00:00:00.000+01:00",
                "lastRenewalDate": "2015-01-08T00:00:00.000+01:00"
              },
              {
                "id" : "22222",
                "name": "Hema Goodbye Mosquito Anti-muggen roller with DEET",
                "categoryType": "Biocide",
                "registrationNumber": "12569",
                "expirationDate": "2017-01-18T00:00:00.000+01:00",
                "lastRenewalDate": "2013-01-17T00:00:00.000+01:00"
              },
              {
                "id" : "55555",
                "name": "TRIFOCIDE VLOEIBAAR DNOC",
                "categoryType": "PPP",
                "registrationNumber": "3204",
                "expirationDate": "2020-01-01T00:00:00.000+01:00",
                "lastRenewalDate": "2013-05-13T00:00:00.000+01:00"
              },
              {
                "id" : "88888",
                "name": "Biopower",
                "categoryType": "Adjuvant",
                "registrationNumber": "13760",
                "expirationDate": "8888-08-07T00:00:00.000+01:00",
                "lastRenewalDate": "2014-06-17T00:00:00.000+01:00"
              }
            ]
        }


## Authorisation [/public-api/1.0/authorisations/{id}{?filter%5Blocale%5D}]

Het opvragen van een authorisation kan resulteren in 3 verschillende types antwoorden:
- Authorisation for Bicode
- Authorisation for Plant Protection Product (PPP)
- Authorisation for Adjuvant

Het `categoryType` in het antwoord document geeft aan welk type toelating het betreft. De waardes hiervoor zijn:
- `Biocide`
- `PPP`
- `Adjuvant`

+ Parameters
    + id: 23456 (number, required) - id van het product.
    + filter%5Blocale%5D: nl (enum[locale], optional) - locale parameter met de afkorting van de gewenste taal. Default is `nl`.
        + Members
                + `nl`
                + `en`


### Request Authorisation  [GET]

+ Response 200 (application/json)


        {
          "data": {
            "id": "da2b87662490471abf72c0d422697647",
            "name": "Wizard",
            "categoryType": "Biocide",
            "userType": "Both",
            "authorisationHolder": {
              "id": "11",
              "companyName": "BAYER",
              "address": {
                "street": "Bayernslaan",
                "number": "888",
                "postalcode": "5635 AE",
                "city": "Ede",
                "country": "England"
              }
            },
            "authorisation": {
              "registrationNumber": {
                "nl": "121212",
                "eu": "EU-1234-9999-000",
                "authorisationStartDate": "2016-12-21T09:25:28.838Z"
              },
              "lastRenewalDate": "2016-12-21T09:25:28.839Z",
              "expirationDate": "2019-12-21T09:25:28.839Z",
              "graceUsageDate": "2018-12-21T09:25:28.840Z",
              "graceSaleDistrDate": "2019-12-21T09:25:28.840Z",
              "instructionsOfUse": [
                {
                  "userType": "Professional",
                  "documents": [
                    {
                      "document": {
                        "docId": "doc-1_456",
                        "documentName": "Besluit.doc.pdf",
                        "link": "doc-1_456_Besluit.doc.pdf"
                      },
                      "lastRenewalDate": "2016-12-21T09:25:28.860Z"
                    }
                  ]
                }
              ]
            },
            "compositions": {
              "formulationType": {
                "id": 1,
                "code": "AE",
                "description": "Aerosol spuitbus"
              },
              "substances": [
                {
                  "substance": {
                    "id": 19,
                    "name": "acefaat",
                    "ecNumber": "250-241-2",
                    "casNumber": "30560-19-1"
                  },
                  "function": {
                    "id": 40,
                    "description": "Werkzame stof"
                  },
                  "concentration": "456",
                  "concentrationUnit": {
                    "id": 20,
                    "unit": "G/L",
                    "description": "gram per liter"
                  }
                }
              ]
            },
            "uses": {
              "generic": {
                "instructionForUse": "InstructionForUse",
                "riskMitigation": "RisicoBeperkendemaatregel",
                "likelyEffects": "effecten en maatregelen"
              },
              "uses": [
                {
                  "nameOfUse": "Arctische Flora",
                  "productType": {
                    "id": 10,
                    "code": "PT01",
                    "description": "Biociden voor menselijke hygiëne"
                  },
                  "description": "Dit is een description toegelaten gebruik",
                  "fieldsOfUse": [
                    {
                      "type": "Indoor",
                      "description": "Binnenshuis"
                    },
                    {
                      "type": "Outdoor",
                      "description": "Buitenshuis"
                    }
                  ],
                  "fieldOfUseDescription": "descriptiongebruiksgebied",
                  "userTypeCategories": [
                    {
                      "type": "GeneralPublic",
                      "description": "Algemeen Publiek",
                      "userType": "NonProfessional"
                    },
                    {
                      "type": "Professional",
                      "description": "Professional",
                      "userType": "Professional"
                    }
                  ],
                  "targetOrganisms": [
                    {
                      "id": 13,
                      "description": "Mijten"
                    }
                  ],
                  "applicationMethods": [
                    {
                      "method": {
                        "id": 13,
                        "description": "Bait application"
                      },
                      "description": "description",
                      "dose": "dose",
                      "dilution": 1,
                      "timing": "aantalTiming"
                    }
                  ],
                  "instructionForUse": {
                    "useInstructions": "specifieke instructies",
                    "riskMitigation": "risicoBeperkendemaatregelen",
                    "likelyEffects": "LikelyEffects",
                    "disposal": "disposal",
                    "storage": "storage"
                  }
                },
                {
                  "nameOfUse": "Arctische Flora",
                  "productType": {
                    "id": 11,
                    "code": "PT02",
                    "description": "Desinfecterende products voor privé-gebruik en voor de openbare gezondheidszorg, alsmede andere desinfectantia"
                  },
                  "description": "Dit is een description toegelaten gebruik",
                  "fieldsOfUse": [
                    {
                      "type": "Indoor",
                      "description": "Binnenshuis"
                    },
                    {
                      "type": "Outdoor",
                      "description": "Buitenshuis"
                    }
                  ],
                  "fieldOfUseDescription": "descriptiongebruiksgebied",
                  "userTypeCategories": [
                    {
                      "type": "GeneralPublic",
                      "description": "Algemeen Publiek",
                      "userType": "NonProfessional"
                    },
                    {
                      "type": "Professional",
                      "description": "Professional",
                      "userType": "Professional"
                    }
                  ],
                  "targetOrganisms": [
                    {
                      "id": 13,
                      "description": "Mijten"
                    }
                  ],
                  "applicationMethods": [
                    {
                      "method": {
                        "id": 13,
                        "description": "Bait application"
                      },
                      "description": "description",
                      "dose": "dose",
                      "dilution": 1,
                      "timing": "aantalTiming"
                    }
                  ],
                  "instructionForUse": {
                    "useInstructions": "specifieke instructies",
                    "riskMitigation": "risicoBeperkendemaatregelen",
                    "likelyEffects": "LikelyEffects",
                    "disposal": "disposal",
                    "storage": "storage"
                  }
                }
              ]
            },
            "decisions": [
              {
                "document": {
                  "docId": "doc-2_789",
                  "documentName": "Bijlage.html.html",
                  "link": "doc-2_789_Bijlage.html.html"
                },
                "decisionType": {
                  "description": "Bijlage"
                },
                "lastRenewalDate": "2016-12-21T09:25:28.860Z"
              },
              {
                "document": {
                  "docId": "doc-1_456",
                  "documentName": "Besluit.doc.pdf",
                  "link": "doc-1_456_Besluit.doc.pdf"
                },
                "decisionType": {
                  "result": "Accept",
                  "description": "Van rechtswege toelating"
                },
                "lastRenewalDate": "2016-12-21T09:25:28.860Z"
              }
            ],
            "motherProduct": {
              "id": "84ae14c6c6a44b7b8d36cf9348022568",
              "name": "Wizard",
              "relationWithMother": "Parallel",
              "registrationNumber": {
                "nl": "121212",
                "eu": "EU-1234-9999-000",
                "authorisationStartDate": "2016-12-21T09:25:28.838Z"
              }
            },
            "components": [
              {
                "name": "ABC",
                "labelling": [
                  {
                    "userType": "Professional",
                    "signalWord": {
                      "descriptionNL": "Gevaar",
                      "descriptionEN": "Danger"
                    },
                    "symbolCodes": [
                      {
                        "code": "GHS07"
                      },
                      {
                        "code": "GHS09"
                      }
                    ],
                    "hazardStatements": [
                      {
                        "code": "H400",
                        "statementNL": "Zeer giftig voor in het water levende organismen.",
                        "statementEN": "Very toxic to aquatic life."
                      },
                      {
                        "code": "H420",
                        "statementNL": "Schadelijk voor de volksgezondheid en het milieu door afbraak van ozon in de bovenste lagen van de atmosfeer.",
                        "statementEN": "Harms public health and the environment by destroying ozone in the upper atmosphere."
                      },
                      {
                        "code": "P231 + P232",
                        "statementNL": "Onder inert gas werken. Tegen vocht beschermen.",
                        "statementEN": "Handle under inert gas. Protect from moisture."
                      }
                    ],
                    "precautionaryStatements": [
                      {
                        "code": "EUH206",
                        "statementNL": "Let op! Niet in combinatie met andere producten gebruiken. Er kunnen gevaarlijke gassen (chloor) vrijkomen.",
                        "statementEN": "Warning! Do not use together with other products. May release dangerous gases (chlorine)."
                      },
                      {
                        "code": "P102",
                        "statementNL": "Buiten het bereik van kinderen houden.",
                        "statementEN": "Keep out of reach of children."
                      },
                      {
                        "code": "P231 + P232",
                        "statementNL": "Onder inert gas werken. Tegen vocht beschermen.",
                        "statementEN": "Handle under inert gas. Protect from moisture."
                      }
                    ],
                    "tactileWarning": false,
                    "childResistantFastening": false,
                    "substancesOnLabel": [
                      {
                        "id": 19,
                        "nameNL": "acefaat",
                        "nameEN": "acephate",
                        "ecNumber": "250-241-2",
                        "casNumber": "30560-19-1"
                      },
                      {
                        "id": 13,
                        "nameNL": "amitrole",
                        "nameEN": "amitrole",
                        "ecNumber": "200-521-5",
                        "casNumber": "61-82-5"
                      },
                      {
                        "id": 2517,
                        "nameNL": "mevinfos",
                        "nameEN": "mevinphos"
                      }
                    ],
                    "extraInfo": "Extra gevaar info"
                  }
                ]
              }
            ]
          }
        }



## Authorisation Biocide [/public-api/1.0/authorisations/22222?{filter%5Blocale%5D}]

Apiary ondersteunt nog geen conditionele responses. Dwz dat het niet mogelijk is om op basis van een product-id verschillende toelating types (Biocides/ppp/Adjuvant) op te vragen.

Een workaround is het toevoegen van een additionele resource, hier toelating met product-id 22222. Deze retourneerd vervolgens de authorisation van een *Biocide*.

+ Parameters
    + filter%5Blocale%5D: nl (enum[locale], optional) - locale parameter met de afkorting van de gewenste taal. Default is `nl`.
        + Members
                + `nl`
                + `en`

### Request Authorisation Biocide [GET]

+ Response 200 (application/json)

        {
          "data": {
            "id": "da2b87662490471abf72c0d422697647",
            "name": "Wizard",
            "categoryType": "Biocide",
            "userType": "Both",
            "authorisationHolder": {
              "id": "11",
              "companyName": "BAYER",
              "address": {
                "street": "Bayernslaan",
                "number": "888",
                "postalcode": "5635 AE",
                "city": "Ede",
                "country": "England"
              }
            },
            "authorisation": {
              "registrationNumber": {
                "nl": "121212",
                "eu": "EU-1234-9999-000",
                "authorisationStartDate": "2016-12-21T09:25:28.838Z"
              },
              "lastRenewalDate": "2016-12-21T09:25:28.839Z",
              "expirationDate": "2019-12-21T09:25:28.839Z",
              "graceUsageDate": "2018-12-21T09:25:28.840Z",
              "graceSaleDistrDate": "2019-12-21T09:25:28.840Z",
              "instructionsOfUse": [
                {
                  "userType": "Professional",
                  "documents": [
                    {
                      "document": {
                        "docId": "doc-1_456",
                        "documentName": "Besluit.doc.pdf",
                        "link": "doc-1_456_Besluit.doc.pdf"
                      },
                      "lastRenewalDate": "2016-12-21T09:25:28.860Z"
                    }
                  ]
                }
              ]
            },
            "compositions": {
              "formulationType": {
                "id": 1,
                "code": "AE",
                "description": "Aerosol spuitbus"
              },
              "substances": [
                {
                  "substance": {
                    "id": 19,
                    "name": "acefaat",
                    "ecNumber": "250-241-2",
                    "casNumber": "30560-19-1"
                  },
                  "function": {
                    "id": 40,
                    "description": "Werkzame stof"
                  },
                  "concentration": "456",
                  "concentrationUnit": {
                    "id": 20,
                    "unit": "G/L",
                    "description": "gram per liter"
                  }
                }
              ]
            },
            "uses": {
              "generic": {
                "instructionForUse": "InstructionForUse",
                "riskMitigation": "RisicoBeperkendemaatregel",
                "likelyEffects": "effecten en maatregelen"
              },
              "uses": [
                {
                  "nameOfUse": "Arctische Flora",
                  "productType": {
                    "id": 10,
                    "code": "PT01",
                    "description": "Biociden voor menselijke hygiëne"
                  },
                  "description": "Dit is een description toegelaten gebruik",
                  "fieldsOfUse": [
                    {
                      "type": "Indoor",
                      "description": "Binnenshuis"
                    },
                    {
                      "type": "Outdoor",
                      "description": "Buitenshuis"
                    }
                  ],
                  "fieldOfUseDescription": "descriptiongebruiksgebied",
                  "userTypeCategories": [
                    {
                      "type": "GeneralPublic",
                      "description": "Algemeen Publiek",
                      "userType": "NonProfessional"
                    },
                    {
                      "type": "Professional",
                      "description": "Professional",
                      "userType": "Professional"
                    }
                  ],
                  "targetOrganisms": [
                    {
                      "id": 13,
                      "description": "Mijten"
                    }
                  ],
                  "applicationMethods": [
                    {
                      "method": {
                        "id": 13,
                        "description": "Bait application"
                      },
                      "description": "description",
                      "dose": "dose",
                      "dilution": 1,
                      "timing": "aantalTiming"
                    }
                  ],
                  "instructionForUse": {
                    "useInstructions": "specifieke instructies",
                    "riskMitigation": "risicoBeperkendemaatregelen",
                    "likelyEffects": "LikelyEffects",
                    "disposal": "disposal",
                    "storage": "storage"
                  }
                },
                {
                  "nameOfUse": "Arctische Flora",
                  "productType": {
                    "id": 11,
                    "code": "PT02",
                    "description": "Desinfecterende products voor privé-gebruik en voor de openbare gezondheidszorg, alsmede andere desinfectantia"
                  },
                  "description": "Dit is een description toegelaten gebruik",
                  "fieldsOfUse": [
                    {
                      "type": "Indoor",
                      "description": "Binnenshuis"
                    },
                    {
                      "type": "Outdoor",
                      "description": "Buitenshuis"
                    }
                  ],
                  "fieldOfUseDescription": "descriptiongebruiksgebied",
                  "userTypeCategories": [
                    {
                      "type": "GeneralPublic",
                      "description": "Algemeen Publiek",
                      "userType": "NonProfessional"
                    },
                    {
                      "type": "Professional",
                      "description": "Professional",
                      "userType": "Professional"
                    }
                  ],
                  "targetOrganisms": [
                    {
                      "id": 13,
                      "description": "Mijten"
                    }
                  ],
                  "applicationMethods": [
                    {
                      "method": {
                        "id": 13,
                        "description": "Bait application"
                      },
                      "description": "description",
                      "dose": "dose",
                      "dilution": 1,
                      "timing": "aantalTiming"
                    }
                  ],
                  "instructionForUse": {
                    "useInstructions": "specifieke instructies",
                    "riskMitigation": "risicoBeperkendemaatregelen",
                    "likelyEffects": "LikelyEffects",
                    "disposal": "disposal",
                    "storage": "storage"
                  }
                }
              ]
            },
            "decisions": [
              {
                "document": {
                  "docId": "doc-2_789",
                  "documentName": "Bijlage.html.html",
                  "link": "doc-2_789_Bijlage.html.html"
                },
                "decisionType": {
                  "description": "Bijlage"
                },
                "lastRenewalDate": "2016-12-21T09:25:28.860Z"
              },
              {
                "document": {
                  "docId": "doc-1_456",
                  "documentName": "Besluit.doc.pdf",
                  "link": "doc-1_456_Besluit.doc.pdf"
                },
                "decisionType": {
                  "result": "Accept",
                  "description": "Van rechtswege toelating"
                },
                "lastRenewalDate": "2016-12-21T09:25:28.860Z"
              }
            ],
            "motherProduct": {
              "id": "84ae14c6c6a44b7b8d36cf9348022568",
              "name": "Wizard",
              "relationWithMother": "Parallel",
              "registrationNumber": {
                "nl": "121212",
                "eu": "EU-1234-9999-000",
                "authorisationStartDate": "2016-12-21T09:25:28.838Z"
              }
            },
            "components": [
              {
                "name": "ABC",
                "labelling": [
                  {
                    "userType": "Professional",
                    "signalWord": {
                      "descriptionNL": "Gevaar",
                      "descriptionEN": "Danger"
                    },
                    "symbolCodes": [
                      {
                        "code": "GHS07"
                      },
                      {
                        "code": "GHS09"
                      }
                    ],
                    "hazardStatements": [
                      {
                        "code": "H400",
                        "statementNL": "Zeer giftig voor in het water levende organismen.",
                        "statementEN": "Very toxic to aquatic life."
                      },
                      {
                        "code": "H420",
                        "statementNL": "Schadelijk voor de volksgezondheid en het milieu door afbraak van ozon in de bovenste lagen van de atmosfeer.",
                        "statementEN": "Harms public health and the environment by destroying ozone in the upper atmosphere."
                      },
                      {
                        "code": "P231 + P232",
                        "statementNL": "Onder inert gas werken. Tegen vocht beschermen.",
                        "statementEN": "Handle under inert gas. Protect from moisture."
                      }
                    ],
                    "precautionaryStatements": [
                      {
                        "code": "EUH206",
                        "statementNL": "Let op! Niet in combinatie met andere producten gebruiken. Er kunnen gevaarlijke gassen (chloor) vrijkomen.",
                        "statementEN": "Warning! Do not use together with other products. May release dangerous gases (chlorine)."
                      },
                      {
                        "code": "P102",
                        "statementNL": "Buiten het bereik van kinderen houden.",
                        "statementEN": "Keep out of reach of children."
                      },
                      {
                        "code": "P231 + P232",
                        "statementNL": "Onder inert gas werken. Tegen vocht beschermen.",
                        "statementEN": "Handle under inert gas. Protect from moisture."
                      }
                    ],
                    "tactileWarning": false,
                    "childResistantFastening": false,
                    "substancesOnLabel": [
                      {
                        "id": 19,
                        "nameNL": "acefaat",
                        "nameEN": "acephate",
                        "ecNumber": "250-241-2",
                        "casNumber": "30560-19-1"
                      },
                      {
                        "id": 13,
                        "nameNL": "amitrole",
                        "nameEN": "amitrole",
                        "ecNumber": "200-521-5",
                        "casNumber": "61-82-5"
                      },
                      {
                        "id": 2517,
                        "nameNL": "mevinfos",
                        "nameEN": "mevinphos"
                      }
                    ],
                    "extraInfo": "Extra gevaar info"
                  }
                ]
              }
            ]
          }
        }


## Authorisation PPP [/public-api/1.0/authorisations/55555{?filter%5Blocale%5D}]

Apiary ondersteunt nog geen conditionele responses. Dwz dat het niet mogelijk is om op basis van een product-id verschillende toelating types (Biocides/ppp/Adjuvant) op te vragen.

Een workaround is het toevoegen van een additionele resource, hier toelating met product-id 55555. Deze retourneerd vervolgens de toelating van een *Plant Protection Product (PPP)*.

+ Parameters
    + filter%5Blocale%5D: nl (enum[locale], optional) - locale parameter met de afkorting van de gewenste taal. Default is `nl`.
        + Members
                + `nl`
                + `en`

### Request Authorisation PPP [GET]

+ Response 200 (application/json)

        {
          "data": {
            "id": "1234",
            "name": "name",
            "categoryType": "PPP",
            "userType": "Professional",
            "authorisationHolder": {
              "id": "11",
              "companyName": "BAYER",
              "address": {
                "street": "Bayernslaan",
                "number": "888",
                "postalcode": "5635 AE",
                "city": "Ede",
                "country": "England"
              }
            },
            "authorisation": {
              "registrationNumber": {
                "nl": "121212",
                "eu": "EU-1234-9999-000",
                "authorisationStartDate": "2016-12-21T09:39:24.232Z"
              },
              "lastRenewalDate": "2016-12-21T09:39:24.237Z",
              "expirationDate": "2016-11-21T09:39:24.765Z",
              "actual": [
                {
                  "userType": "Professional",
                  "wCodings": [
                    {
                      "wCode": "W1",
                      "instructionOfUse": {
                        "document": {
                          "docId": "doc-1_456",
                          "documentName": "v2.pdf",
                          "link": "doc-1_456_v2.pdf"
                        },
                        "lastRenewalDate": "2016-12-21T09:39:24.247Z"
                      },
                      "authorisationStartDate": "2016-12-21T09:39:24.767Z",
                      "expirationDate": "2016-11-21T09:39:24.765Z"
                    }
                  ]
                }
              ],
              "previous": [
                {
                  "userType": "Professional",
                  "wCodings": [
                    {
                      "instructionOfUse": {
                        "document": {
                          "docId": "doc-1_456",
                          "documentName": "v1.pdf",
                          "link": "doc-1_456_v1.pdf"
                        },
                        "lastRenewalDate": "2016-12-21T09:39:24.247Z"
                      },
                      "authorisationStartDate": "2016-12-21T09:39:24.767Z",
                      "expirationDate": "2016-11-21T09:39:24.765Z",
                      "graceUsageDate": "2015-12-21T09:39:24.765Z",
                      "graceSaleDistrDate": "2014-12-21T09:39:24.765Z"
                    }
                  ]
                }
              ]
            },
            "outcomeTypes": [
              {
                "id": 1,
                "description": "acaricide"
              },
              {
                "id": 2,
                "description": "bactericide"
              }
            ],
            "compositions": {
              "formulationType": {
                "id": 1,
                "code": "AE",
                "description": "Aerosol spuitbus"
              },
              "substances": [
                {
                  "substance": {
                    "id": 19,
                    "name": "acefaat",
                    "ecNumber": "250-241-2",
                    "casNumber": "30560-19-1"
                  },
                  "function": {
                    "id": 40,
                    "description": "Werkzame stof"
                  },
                  "concentration": "456",
                  "concentrationUnit": {
                    "id": 20,
                    "unit": "G/L",
                    "description": "gram per liter"
                  }
                },
                {
                  "substance": {
                    "id": 12,
                    "name": "aluminiumfosfide",
                    "ecNumber": "244-088-0",
                    "casNumber": "20859-73-8"
                  },
                  "function": {
                    "id": 40,
                    "description": "Werkzame stof"
                  },
                  "concentration": "456",
                  "concentrationUnit": {
                    "id": 20,
                    "unit": "G/KG",
                    "description": "gram per kilogram"
                  }
                }
              ]
            },
            "uses": [
              {
                "nameOfUse": "Herbiciden",
                "targetOrganism": {
                  "id": 0,
                  "description": "Geclaimd organise"
                },
                "targetLocations": [
                  {
                    "id": 1,
                    "description": "Bedekt"
                  },
                  {
                    "id": 2,
                    "description": "Onbedekt"
                  }
                ],
                "dtgVersion": "2.1",
                "targetCrops": [
                  {
                    "group": "Akkerbouwgewassen",
                    "items": [
                      {
                        "group": "Aardappelen",
                        "items": [
                          {
                            "crop": "Pootaardappel",
                            "eppo": [
                              "SOLTU"
                            ],
                            "limitedTo": "Piepers",
                            "attractiveToHoneybees": true,
                            "remarksHoneybees": "Voor pollen",
                            "cropCyclesUncoveredYear": "1",
                            "selected": true
                          }
                        ],
                        "selected": false,
                        "complete": false
                      },
                      {
                        "group": "Bieten",
                        "items": [],
                        "attractiveToHoneybees": false,
                        "selected": true,
                        "complete": false
                      }
                    ],
                    "selected": false,
                    "complete": false
                  }
                ],
                "growthStage": {
                  "from": 10,
                  "to": 40
                },
                "applicationTiming": {
                  "fromMonth": 2,
                  "toMonth": 12
                },
                "amountOfApplications": {
                  "perUse": 10,
                  "perCropSeason": 8
                },
                "minimumIntervalBetweenApplications": 4,
                "maximumProductDose": {
                  "ratio": 2,
                  "scale": 4,
                  "measure": {
                    "id": 14,
                    "unit": "kg/ton"
                  }
                },
                "maximumProductDosePerCropSeason": {
                  "ratio": 4,
                  "scale": 3,
                  "measure": {
                    "id": 14,
                    "unit": "g/kg zaad"
                  }
                },
                "watervolumeScale": {
                  "min": 4,
                  "max": 100
                },
                "isWatervolumeDependingOnGrowthStage": true,
                "phiDays": 4,
                "seedDensity": 5,
                "remarks": "remarks"
              },
              {
                "nameOfUse": "Insecticiden",
                "targetOrganism": {
                  "id": 0,
                  "description": "Geclaimd organisme"
                },
                "targetLocations": [
                  {
                    "id": 1,
                    "description": "Bedekt"
                  },
                  {
                    "id": 2,
                    "description": "Onbedekt"
                  }
                ],
                "dtgVersion": "2.1",
                "targetCrops": [
                  {
                    "group": "Akkerbouwgewassen",
                    "items": [
                      {
                        "group": "Aardappelen",
                        "items": [
                          {
                            "crop": "Pootaardappel",
                            "eppo": [
                              "SOLTU"
                            ],
                            "limitedTo": "Piepers",
                            "attractiveToHoneybees": true,
                            "remarksHoneybees": "Voor pollen",
                            "cropCyclesUncoveredYear": "1",
                            "selected": true
                          }
                        ],
                        "selected": false,
                        "complete": false
                      },
                      {
                        "group": "Bieten",
                        "items": [],
                        "attractiveToHoneybees": false,
                        "selected": true,
                        "complete": false
                      }
                    ],
                    "selected": false,
                    "complete": false
                  }
                ],
                "growthStage": {
                  "from": 20,
                  "to": 30
                },
                "applicationTiming": {
                  "fromMonth": 3,
                  "toMonth": 4
                },
                "amountOfApplications": {
                  "perUse": 4,
                  "perCropSeason": 3
                },
                "minimumIntervalBetweenApplications": 4,
                "maximumProductDose": {
                  "ratio": 2,
                  "scale": 4,
                  "measure": {
                    "id": 14,
                    "unit": "kg/ton"
                  }
                },
                "maximumProductDosePerCropSeason": {
                  "ratio": 4,
                  "scale": 3,
                  "measure": {
                    "id": 14,
                    "unit": "g/kg zaad"
                  }
                },
                "watervolumeScale": {
                  "min": 2,
                  "max": 10
                },
                "isWatervolumeDependingOnGrowthStage": true,
                "phiDays": 4
              }
            ],
            "decisions": [
              {
                "document": {
                  "docId": "doc-1_456",
                  "documentName": "Besluit.doc.pdf",
                  "link": "doc-1_456_Besluit.doc.pdf"
                },
                "decisionType": {
                  "result": "Accept",
                  "description": "Van rechtswege toelating"
                },
                "lastRenewalDate": "2016-12-21T09:39:24.247Z"
              }
            ],
            "components": [
              {
                "name": "ABC",
                "labelling": [
                  {
                    "userType": "Professional",
                    "signalWord": {
                      "descriptionNL": "Gevaar",
                      "descriptionEN": "Danger"
                    },
                    "symbolCodes": [
                      {
                        "code": "GHS07"
                      },
                      {
                        "code": "GHS09"
                      }
                    ],
                    "hazardStatements": [
                      {
                        "code": "H400",
                        "statementNL": "Zeer giftig voor in het water levende organismen.",
                        "statementEN": "Very toxic to aquatic life."
                      },
                      {
                        "code": "H420",
                        "statementNL": "Schadelijk voor de volksgezondheid en het milieu door afbraak van ozon in de bovenste lagen van de atmosfeer.",
                        "statementEN": "Harms public health and the environment by destroying ozone in the upper atmosphere."
                      },
                      {
                        "code": "P231 + P232",
                        "statementNL": "Onder inert gas werken. Tegen vocht beschermen.",
                        "statementEN": "Handle under inert gas. Protect from moisture."
                      }
                    ],
                    "precautionaryStatements": [
                      {
                        "code": "EUH206",
                        "statementNL": "Let op! Niet in combinatie met andere producten gebruiken. Er kunnen gevaarlijke gassen (chloor) vrijkomen.",
                        "statementEN": "Warning! Do not use together with other products. May release dangerous gases (chlorine)."
                      },
                      {
                        "code": "P102",
                        "statementNL": "Buiten het bereik van kinderen houden.",
                        "statementEN": "Keep out of reach of children."
                      },
                      {
                        "code": "P231 + P232",
                        "statementNL": "Onder inert gas werken. Tegen vocht beschermen.",
                        "statementEN": "Handle under inert gas. Protect from moisture."
                      }
                    ],
                    "tactileWarning": false,
                    "childResistantFastening": false,
                    "substancesOnLabel": [
                      {
                        "id": 19,
                        "nameNL": "acefaat",
                        "nameEN": "acephate",
                        "ecNumber": "250-241-2",
                        "casNumber": "30560-19-1"
                      },
                      {
                        "id": 13,
                        "nameNL": "amitrole",
                        "nameEN": "amitrole",
                        "ecNumber": "200-521-5",
                        "casNumber": "61-82-5"
                      },
                      {
                        "id": 2517,
                        "nameNL": "mevinfos",
                        "nameEN": "mevinphos"
                      }
                    ],
                    "extraInfo": "Extra gevaar info"
                  }
                ]
              }
            ]
          }
        }





## Authorisation Adjuvant [/public-api/1.0/authorisations/88888{?filter%5Blocale%5D}]

Apiary ondersteunt nog geen conditionele responses. Dwz dat het niet mogelijk is om op basis van een product-id verschillende toelating types (Biocides/ppp/Adjuvant) op te vragen.

Een workaround is het toevoegen van een additionele resource, hier toelating met product-id 88888. Deze retourneerd vervolgens de toelating van een *Adjuvant*.

+ Parameters
    + filter%5Blocale%5D: nl (enum[locale], optional) - locale parameter met de afkorting van de gewenste taal. Default is `nl`.
        + Members
                + `nl`
                + `en`

### Request Authorisation Adjuvant [GET]

+ Response 200 (application/json)

        {
          "data": {
            "id": "a723681a55f6474787c59dfc2908a723",
            "name": "Wizard",
            "categoryType": "Adjuvant",
            "userType": "NonProfessional",
            "authorisationHolder": {
              "id": "11",
              "companyName": "BAYER",
              "address": {
                "street": "Bayernslaan",
                "number": "888",
                "postalcode": "5635 AE",
                "city": "Ede",
                "country": "England"
              }
            },
            "authorisation": {
              "registrationNumber": {
                "nl": "121212",
                "eu": "EU-1234-9999-000",
                "authorisationStartDate": "2016-12-20T14:51:30.070Z"
              },
              "expirationDate": "2019-12-20T14:51:30.080Z",
              "instructionsOfUse": [
                {
                  "userType": "Professional",
                  "documents": [
                    {
                      "document": {
                        "docId": "doc-1_456",
                        "documentName": "Besluit.doc.pdf",
                        "link": "doc-1_456_Besluit.doc.pdf"
                      },
                      "lastRenewalDate": "2016-12-20T14:51:30.095Z"
                    }
                  ]
                }
              ],
              "lastRenewalDate": "2016-12-20T14:51:30.080Z"
            },
            "decisions": [
              {
                "document": {
                  "docId": "doc-2_789",
                  "documentName": "Bijlage.html.html",
                  "link": "doc-2_789_Bijlage.html.html"
                },
                "decisionType": {
                  "description": "Bijlage"
                },
                "lastRenewalDate": "2016-12-20T14:51:30.095Z"
              },
              {
                "document": {
                  "docId": "doc-1_456",
                  "documentName": "Besluit.doc.pdf",
                  "link": "doc-1_456_Besluit.doc.pdf"
                },
                "decisionType": {
                  "result": "Accept",
                  "description": "Van rechtswege toelating"
                },
                "lastRenewalDate": "2016-12-20T14:51:30.095Z"
              }
            ]
          }
        }



## Masterdata Substances [/public-api/1.0/masterdata/substances{?filter%5Bfunction%5D,filter%5Bquery%5D,filter%5Blocale%5D,page%5Boffset%5D,page%5Blimit%5D}]

Met deze service kunnen stoffen opgezocht worden. Deze service ondersteunt paginatie.

+ Parameters
    + filter%5Bfunction%5D (enum[function], required) - de function van de substance.
        + Members
            + `ActiveSubstance`
            + `Safener`
    + filter%5Bquery%5D: ben (string, required) - query parameter met een deel van een substance attribute zijnde, `name`, `ecNumber` of `casNumber`. In de zoekvraag wordt dit vertaald naar: `name`, `ecNumber` of `casNumber` `contains query`, niet hoofdlettergevoelig
    + filter%5Blocale%5D: nl (enum[lang], optional) - locale parameter met de afkorting van de gewenste taal. Default is `nl`.
        + Members
                + `nl`
                + `en`
    + page%5Boffset%5D (number, optional) -  aantal substances die overgeslagen worden voordat het resultaat geretourneerd wordt
        + Default: `0`
    + page%5Blimit%5D (number, optional) - aantal te retourneren substances
        + Default: `100`


### Request Substances [GET]

+ Response 200 (application/json)

        {
            "meta": {
                "total": 734,
                "offset":0,
                "limit":100
            },
            "data": [
                {"name":"(1-methylethyl)benzenesulfonic acid, sodium salt", "casNumber":"28348-53-0","id":10601},
                {"ecNumber":"230-515-8","name":"(2-bromo-2-nitroethenyl)benzene","casNumber":"7166-19-0","id":6939},
                {"ecNumber":"244-445-0","name":"(benzothiazol-2-ylthio)methyl thiocyanate", "casNumber":"21564-17-0","id":7218},
                {"ecNumber":"238-588-8","name":"benzylhemiformal","casNumber":"14548-60-8","id":10022},
                {"ecNumber":"215-551-4","name":"(dodecylbenzyl)trimethylammonium chloride","casNumber":"1330-85-4","id":2372}
                ]
            }


## Masterdata Authorisationholders [/public-api/1.0/masterdata/authorisationholders{?filter%5Bquery%5D,page%5Boffset%5D,page%5Blimit%5D}]

Met deze service kunnen authorisationholders opgezocht worden. Deze service ondersteunt paginatie.

+ Parameters
    + filter%5Bquery%5D: a (string, optional) -  naam van het bedrijf or een deel ervan. In de zoekvraag wordt dit vertaald naar `contains naam`, niet hoofdlettergevoelig
    + page%5Boffset%5D (number, optional) -  aantal authorisationholders die overgeslagen worden voordat het resultaat geretourneerd wordt
        + Default: `0`
    + page%5Blimit%5D (number, optional) - aantal te retourneren toelatinghouders
        + Default: `100`


### Request Authorisationholders [GET]

+ Response 200 (application/json)

        {
            "meta": {
                "total": 1255,
                "offset":0,
                "limit":100
            },
            "data": [
                {"id":"9384adf1212", "companyName" : "BAYER", "address" : {"street" : "Bayernslaan","number" : "888", "postalcode" : "5635 AE", "city" : "Ede", "country" : "Engcountry"}},
                {"id":"32323ad1213", "companyName":"Wacon Aquaven B.V.","address":{"street":"Noorderhaven","number":"100","postalcode":"8861 AR","city":"Harlingen","country":"Nedercountry"}},
                {"id":"12ddaerwe17", "companyName":"FA. S. V.D. WERF","address":{"street":"Cartografenweg","number":"34","postalcode":"5141 MT","city":"Waalwijk","country":"Nedercountry"}},
                {"id":"33434ss1230", "companyName":"Techno Trading Holcountry","address":{"street":"Groesweg","number":"13","postalcode":"5993 NN","city":"Maasbree","country":"Nedercountry"}}
            ]
        }

## Productcodes voor Biocides [/public-api/1.0/masterdata/biocide/productcodes{?filter%5Bquery%5D,filter%5Blocale%5D,page%5Boffset%5D,page%5Blimit%5D}]

Met deze service kunnen productcodes (PT-Codes) voor Biocides opgezocht worden. Deze service ondersteunt paginatie.

+ Parameters
    + filter%5Bquery%5D: PT0 (string, optional) - query parameter met PT code, description of een deel ervan. In de zoekvraag wordt dit vertaald naar `contains naam`, niet hoofdlettergevoelig
    + filter%5Blocale%5D: nl (enum[lang], optional) - locale parameter met de afkorting van de gewenste taal. Default is `nl`.
        + Members
                + `nl`
                + `en`
    + page%5Boffset%5D (number, optional) -  aantal productcodes die overgeslagen worden voordat het resultaat geretourneerd wordt
        + Default: `0`
    + page%5Blimit%5D (number, optional) - aantal te retourneren productcodes
        + Default: `100`


### Request Procutcodes voor Biocides [GET]

+ Response 200 (application/json)

        {
            "meta": {
                "total": 1255,
                "offset":0,
                "limit":100
            },
            "data": [{
                  "id" : 1,
                  "code" : "PT01",
                  "description" : "Biociden voor menselijke hygiëne",
                  "echaCode" : "PT01"
                }, {
                  "id" : 2,
                  "code" : "PT02",
                  "description" : "Desinfecterende products voor privé-userType en voor de openbare gezondheidszorg, alsmede andere desinfectantia",
                  "echaCode" : "PT02"
                }, {
                  "id" : 3,
                  "code" : "PT03",
                  "description" : "Biociden voor veterinaire hygiëne-doeleinden",
                  "echaCode" : "PT03"
                }]
        }


## Targetorganisms voor Biocides [/public-api/1.0/masterdata/biocide/targetorganisms{?filter%5Bquery%5D,filter%5Blocale%5D,page%5Boffset%5D,page%5Blimit%5D}]

Met deze service kunnen triviale namen van targetorganisms voor Biocides opgezocht worden. Deze service ondersteunt paginatie.

+ Parameters
    + filter%5Bquery%5D: Acarid (string, optional) - query parameter met een triviale organisme naam of een deel ervan. In de zoekvraag wordt dit vertaald naar `contains naam`, niet hoofdlettergevoelig
    + filter%5Blocale%5D: nl (enum[lang], optional) - locale parameter met de afkorting van de gewenste taal. Default is `nl`.
        + Members
                + `nl`
                + `en`
    + page%5Boffset%5D (number, optional) -  aantal targetOrganisms die overgeslagen worden voordat het resultaat geretourneerd wordt
        + Default: `0`
    + page%5Blimit%5D (number, optional) - aantal te retourneren targetOrganisms
        + Default: `100`


### Request Targetorganisms voor Biocides [GET]

+ Response 200 (application/json)

        {
            "meta": {
                "total": 1255,
                "offset":0,
                "limit":100
            },
            "data": [
                {"id": 1, "echaCode": "4998", "description": "Acarid mites"},
                {"id": 2, "description": "Adults | Ants"},
                {"id": 3, "echaCode": "4999", "description": "Aedes mosquitoes"},
                {"id": 4, "echaCode": "5794", "description": "Algae"}
              ]
        }

## Targetorganisms voor PPPs [/public-api/1.0/masterdata/ppp/targetorganisms{?filter%5Bquery%5D,filter%5Blocale%5D,page%5Boffset%5D,page%5Blimit%5D}]

Met deze service kunnen targetorganisms van PPP opgevraagd worden. Deze service ondersteunt paginatie.

+ Parameters
    + filter%5Bquery%5D: ar (string, optional) - query parameter met targetOrganism of een deel ervan. In de zoekvraag wordt dit vertaald naar `contains naam`, niet hoofdlettergevoelig
    + filter%5Blocale%5D: nl (enum[lang], optional) - locale parameter met de afkorting van de gewenste taal. Default is `nl`.
        + Members
                + `nl`
                + `en`
    + page%5Boffset%5D (number, optional) -  aantal  target organisms die overgeslagen worden voordat het resultaat geretourneerd wordt
        + Default: `0`
    + page%5Blimit%5D (number, optional) - aantal te retourneren target organisms
        + Default: `100`


### Request Targetorganisms voor PPPs [GET]

+ Response 200 (application/json)

        {
            "meta": {
                "total": 1255,
                "offset":0,
                "limit":100
            },
            "data": [
                    {"id": 1, "description": "TBD-nl-1"},
                    {"id": 2, "description": "TBD-nl-2"}
                ]
        }


## Targetcrops voor PPPs [/public-api/1.0/masterdata/ppp/targetcrops{?filter%5Bquery%5D,filter%5Blocale%5D,page%5Boffset%5D,page%5Blimit%5D}]

Met deze service kunnen targetcrops van PPP gebaseerd op Definitielijsten Toepassingsgebieden Gewasbeschermingsmiddelen (DTG) opgevraagd worden. Deze service ondersteunt paginatie.

+ Parameters
    + filter%5Bquery%5D: ar (string, optional) - query parameter met plant, group of eppo code of een deel ervan. In de zoekvraag wordt dit vertaald naar `contains naam`, niet hoofdlettergevoelig
    + filter%5Blocale%5D: nl (enum[lang], optional) - locale parameter met de afkorting van de gewenste taal. Default is `nl`.
        + Members
                + `nl`
                + `en`
    + page%5Boffset%5D (number, optional) -  aantal gewassen die overgeslagen worden voordat het resultaat geretourneerd wordt
        + Default: `0`
    + page%5Blimit%5D (number, optional) - aantal te retourneren gewassen
        + Default: `100`



### Request Targetcrops voor PPPs [GET]

+ Response 200 (application/json)

        {
            "meta": {
                "total": 1255,
                "offset":0,
                "limit":100
            },
            "data": [{
                "name": "Aardpeer",
                "type": "group"
              },
              {
                "name": "Japanse aardappel",
                "type": "plant"
              },
              {
                "name": "Knoflook",
                "type": "subgroup"
              },
              {
                "name": "STARB",
                "type": "eppo"
              }
            ]
        }


## Targetlocations voor PPPs [/public-api/1.0/masterdata/ppp/targetlocations{?filter%5Bquery%5D,filter%5Blocale%5D,page%5Boffset%5D,page%5Blimit%5D}]

Met deze service kunnen targetlocations voor PPPs opgezocht worden. Deze service ondersteunt paginatie.

+ Parameters
    + filter%5Bquery%5D: Bede (string, required) - query parameter met een targetlocations of een deel ervan. In de zoekvraag wordt dit vertaald naar `contains naam`, niet hoofdlettergevoelig
    + filter%5Blocale%5D: nl (enum[lang], optional) - locale parameter met de afkorting van de gewenste taal. Default is `nl`.
        + Members
                + `nl`
                + `en`
    + page%5Boffset%5D (number, optional) -  aantal targetlocations die overgeslagen worden voordat het resultaat geretourneerd wordt
        + Default: `0`
    + page%5Blimit%5D (number, optional) - aantal te retourneren targetlocations
        + Default: `100`


### Request Targetlocations voor PPPs [GET]

+ Response 200 (application/json)

        {
            "meta": {
                "total": 1255,
                "offset":0,
                "limit":100
            },
            "data": [
                    {"id": 1, "description": "Bedekt"},
                    {"id": 2, "description": "Onbedekt"}
                ]
        }




## Outcometypes voor PPPs [/public-api/1.0/masterdata/ppp/outcometypes{?filter%5Bquery%5D,filter%5Blocale%5D,page%5Boffset%5D,page%5Blimit%5D}]

Met deze service kunnen outcometypes voor PPP opgezocht worden. Deze service ondersteunt paginatie.

+ Parameters
    + filter%5Bquery%5D: Bede (string, required) - query parameter met aard werking of een deel ervan. In de zoekvraag wordt dit vertaald naar `contains naam`, niet hoofdlettergevoelig
    + filter%5Blocale%5D: nl (enum[lang], optional) - locale parameter met de afkorting van de gewenste taal. Default is `nl`.
        + Members
                + `nl`
                + `en`
    + page%5Boffset%5D (number, optional) -  aantal aard werkingen die overgeslagen worden voordat het resultaat geretourneerd wordt
        + Default: `0`
    + page%5Blimit%5D (number, optional) - aantal te retourneren aard werkingen
        + Default: `100`


### Request Outcometypes voor PPPs [GET]

+ Response 200 (application/json)

        {
            "meta": {
                "total": 1255,
                "offset":0,
                "limit":100
            },
            "data": [
                    {"id": 1, "description": "Werking-1"},
                    {"id": 2, "description": "Werking-2"}
                ]
        }